// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Pau Aliagas <linuxnow@gmail.com>
/*
 * omxdsp_perturb.c — built twice by test/perturb.sh: against a perturbed omx_contract_limits.h
 * (OMXDSP_PERTURBED defined; 96000 dropped from the declared rates, the comp's ratio floor and the
 * opto release's fastMs moved) and against the real one.
 * A perturbed build must see the drop through the contracts; the control must not.
 *
 * Each primitive's case lives in its own test/kernels/<name>.perturb.c
 * (`static int perturb_<name>(int failed)`) instead of being appended here —
 * tools/kernels-gen.sh collects them (sorted by filename, never committed) into the include
 * below.
 */
#define OMX_CONTRACT_STORAGE 1
#include <omxdsp/omxdsp.h>

#include <stdio.h>
#include <string.h>

/* GENERATED by tools/kernels-gen.sh from every test/kernels/ perturb file (sorted by filename) —
 * declares every perturb_<name>(int) and OMXDSP_PERTURBS[]/OMXDSP_PERTURB_COUNT. Not committed. */
#include "kernels-perturb.inc.c"

int main(void) {
  int failed = 0;
  for (int i = 0; i < OMXDSP_PERTURB_COUNT; i++) failed = OMXDSP_PERTURBS[i](failed);
  return failed == 0 ? 0 : 1;
}
