// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Pau Aliagas <linuxnow@gmail.com>
/*
 * omxdsp_suite.c — the library suite: every primitive's oracle at every declared rate, with
 * contracts ON, ending on an EMPTY ledger (docs/design/specs/2026-09-26-dsp-primitives.md §8b).
 * Pure C, -lm, no other package.
 *
 * Each primitive's arm lives in its own file under test/kernels/ (`static void arm_<name>(void)`,
 * filename `<name>.c`) instead of being appended here: two kernel lanes adding an arm each used
 * to both edit this file's main(), on the same lines. `tools/kernels-gen.sh` globs test/kernels/
 * sorted by filename and writes the include list + call array below into a build artefact this
 * file pulls in — never committed, never hand-edited
 * (docs/design/specs/2026-09-15-no-stored-derivations.md).
 */
#define OMX_CONTRACT_STORAGE 1
#include <omxdsp/omxdsp.h>

#include <complex.h>
#include <math.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ---- the harness -------------------------------------------------------------------------- */

static int g_checks = 0, g_failed = 0;
static const char *g_arm = "";

static void ok(int cond, const char *what, double measured, double limit) {
  g_checks++;
  if (!cond) {
    g_failed++;
    printf("FAIL [%s] %s — measured %.9g, limit %.9g\n", g_arm, what, measured, limit);
  }
}

/* Every violation the ledger holds, printed, then the ledger is expected empty for this arm. */
static void expect_clean(void) {
  const uint32_t seen = omx_contract_log.count;
  const uint32_t kept = seen < OMX_CONTRACT_MAX ? seen : OMX_CONTRACT_MAX;
  for (uint32_t i = 0; i < kept; i++) {
    const struct omx_contract_record *r = &omx_contract_log.rec[i];
    if (!omx_contract_record_ready(r)) continue;
    printf("VIOLATION [%s] %s %s (frame %u)\n", r->stage, r->kind, r->token, r->frame);
  }
  ok(seen == 0u, "no contract violation in this arm", (double)seen, 0.0);
  omx_contract_reset();
}

static uint32_t g_seed = 0x2f6e2b1du;
static float rnd(float lo, float hi) {
  g_seed ^= g_seed << 13;
  g_seed ^= g_seed >> 17;
  g_seed ^= g_seed << 5;
  return lo + (hi - lo) * ((float)(g_seed >> 8) / 16777216.0f);
}

/* GENERATED by tools/kernels-gen.sh from every file under test/kernels/ (sorted by filename) —
 * declares every arm_<name>(void) and OMXDSP_ARMS[]/OMXDSP_ARM_COUNT. Not committed; the
 * Makefile runs the generator before this file is compiled. */
#include "kernels-suite.inc.c"

int main(void) {
  omx_contract_reset();
  for (int i = 0; i < OMXDSP_ARM_COUNT; i++) OMXDSP_ARMS[i]();
  const uint32_t violations = omx_contract_log.count;
  const uint32_t evaluated = omx_contract_log.checks;
  printf("omxdsp_suite: %d checks, %d failed; %u contracts evaluated, %u violations left\n", g_checks,
         g_failed, evaluated, violations);
  if (evaluated < 1000u) {
    printf("FAIL the suite evaluated %u contracts — floor is 1000\n", evaluated);
    return 1;
  }
  if (violations != 0u) return 1;
  return g_failed == 0 ? 0 : 1;
}
