#ifndef OMX_CONTRACT_LIMITS_H
#define OMX_CONTRACT_LIMITS_H
/*
 * GENERATED — DO NOT EDIT BY HAND.
 * Produced by harness/contract-limits-gen.mjs from packages/core/src/channel-contract.ts's
 * `laws` column (R-056), every table packages/core/src/native-limit-tables.ts's registry
 * holds, packages/core/src/control-bounds.ts's CORE_LIMITS for the pan/delay/reverb/drive
 * facts, EVERY declared scalar and all-number sheet packages/core/src/declared-scalars.ts
 * discovers over the core barrel and @freemixer/declarations (dsp-primitives §7), and
 * packages/core/src/row-codecs.ts's STANDARD_SAMPLE_RATES. Regenerate:
 * `node harness/contract-limits-gen.mjs`, then commit the result — see this file's own
 * generator for why it is committed rather than gitignored.
 *
 * A C contract (OMX_PRE/OMX_POST/OMX_INVARIANT) reads a limit from HERE, never a literal:
 * packages/server/src/contract-limits-generated-conformance.test.ts refuses both a stale
 * header and a C literal that duplicates a number this file already declares.
 */

/* The closed law vocabulary (core's LAW_KINDS, fact-declaration.ts) — one member per law. */
typedef enum {
  OMX_LAW_NO_GAIN_ADDED = 0,
  OMX_LAW_OUTPUT_LE_INPUT_PLUS,
  OMX_LAW_UNITY_AT_DEFAULT,
  OMX_LAW_DELAYED_COPY,
  OMX_LAW_BYPASS_IDENTITY,
  OMX_LAW_TAIL_DECAYS,
  OMX_LAW_CONSTANT_POWER_PAN,
  OMX_LAW_LINEAR_SUM,
  OMX_LAW_FINITE,
  OMX_LAW_NO_DENORMAL_STATE,
} omx_contract_law_t;

/* Per-stage law lists, one per channel fact whose row declares `laws` — the SAME array
 * harness/contracts-scaffold.mjs's applier and the MCP contract_laws tool read; a stage's
 * OMX_POST tokens implement one or more of these, never a second spelling of the law. */
static const omx_contract_law_t OMX_STAGE_LAWS_PAN[] = { OMX_LAW_FINITE, OMX_LAW_CONSTANT_POWER_PAN };
#define OMX_STAGE_LAWS_PAN_COUNT 2

static const omx_contract_law_t OMX_STAGE_LAWS_EQ[] = { OMX_LAW_FINITE, OMX_LAW_NO_DENORMAL_STATE, OMX_LAW_BYPASS_IDENTITY };
#define OMX_STAGE_LAWS_EQ_COUNT 3

static const omx_contract_law_t OMX_STAGE_LAWS_GATE[] = { OMX_LAW_FINITE, OMX_LAW_NO_DENORMAL_STATE, OMX_LAW_BYPASS_IDENTITY, OMX_LAW_NO_GAIN_ADDED, OMX_LAW_UNITY_AT_DEFAULT };
#define OMX_STAGE_LAWS_GATE_COUNT 5

static const omx_contract_law_t OMX_STAGE_LAWS_DYNAMICS[] = { OMX_LAW_FINITE, OMX_LAW_NO_DENORMAL_STATE, OMX_LAW_BYPASS_IDENTITY, OMX_LAW_OUTPUT_LE_INPUT_PLUS, OMX_LAW_UNITY_AT_DEFAULT };
#define OMX_STAGE_LAWS_DYNAMICS_COUNT 5

static const omx_contract_law_t OMX_STAGE_LAWS_DELAY[] = { OMX_LAW_FINITE, OMX_LAW_BYPASS_IDENTITY, OMX_LAW_DELAYED_COPY };
#define OMX_STAGE_LAWS_DELAY_COUNT 3

static const omx_contract_law_t OMX_STAGE_LAWS_REVERB[] = { OMX_LAW_FINITE, OMX_LAW_NO_DENORMAL_STATE, OMX_LAW_BYPASS_IDENTITY, OMX_LAW_TAIL_DECAYS };
#define OMX_STAGE_LAWS_REVERB_COUNT 4

static const omx_contract_law_t OMX_STAGE_LAWS_DRIVE[] = { OMX_LAW_FINITE, OMX_LAW_BYPASS_IDENTITY, OMX_LAW_UNITY_AT_DEFAULT };
#define OMX_STAGE_LAWS_DRIVE_COUNT 3

static const omx_contract_law_t OMX_STAGE_LAWS_DEESSER[] = { OMX_LAW_FINITE, OMX_LAW_NO_DENORMAL_STATE, OMX_LAW_BYPASS_IDENTITY, OMX_LAW_NO_GAIN_ADDED };
#define OMX_STAGE_LAWS_DEESSER_COUNT 4

static const omx_contract_law_t OMX_STAGE_LAWS_CHORUS[] = { OMX_LAW_FINITE, OMX_LAW_BYPASS_IDENTITY };
#define OMX_STAGE_LAWS_CHORUS_COUNT 2

static const omx_contract_law_t OMX_STAGE_LAWS_FLANGER[] = { OMX_LAW_FINITE, OMX_LAW_NO_DENORMAL_STATE, OMX_LAW_BYPASS_IDENTITY };
#define OMX_STAGE_LAWS_FLANGER_COUNT 3

static const omx_contract_law_t OMX_STAGE_LAWS_TOMAIN[] = { OMX_LAW_FINITE, OMX_LAW_LINEAR_SUM };
#define OMX_STAGE_LAWS_TOMAIN_COUNT 2

/* Per-parameter numeric travel, one block per table registered in
 * packages/core/src/native-limit-tables.ts (GATE/COMP today; a kernel that registers a table
 * lands here because it is REGISTERED, not because this generator names it). */
#define OMX_COMP_THRESHOLD_DB_MIN -60.0f
#define OMX_COMP_THRESHOLD_DB_MAX 0.0f
#define OMX_COMP_THRESHOLD_DB_DEFAULT -18.0f
#define OMX_COMP_RATIO_MIN 1.0f
#define OMX_COMP_RATIO_MAX 20.0f
#define OMX_COMP_RATIO_DEFAULT 4.0f
#define OMX_COMP_KNEE_DB_MIN 0.0f
#define OMX_COMP_KNEE_DB_MAX 24.0f
#define OMX_COMP_KNEE_DB_DEFAULT 6.0f
#define OMX_COMP_ATTACK_MS_MIN 0.1f
#define OMX_COMP_ATTACK_MS_MAX 100.0f
#define OMX_COMP_ATTACK_MS_DEFAULT 5.0f
#define OMX_COMP_RELEASE_MS_MIN 5.0f
#define OMX_COMP_RELEASE_MS_MAX 3000.0f
#define OMX_COMP_RELEASE_MS_DEFAULT 200.0f
#define OMX_COMP_MAKEUP_DB_MIN 0.0f
#define OMX_COMP_MAKEUP_DB_MAX 24.0f
#define OMX_COMP_MAKEUP_DB_DEFAULT 0.0f
#define OMX_COMP_MIX_PCT_MIN 0.0f
#define OMX_COMP_MIX_PCT_MAX 100.0f
#define OMX_COMP_MIX_PCT_DEFAULT 100.0f

#define OMX_GATE_THRESHOLD_DB_MIN -80.0f
#define OMX_GATE_THRESHOLD_DB_MAX 0.0f
#define OMX_GATE_THRESHOLD_DB_DEFAULT -40.0f
#define OMX_GATE_RANGE_DB_MIN -90.0f
#define OMX_GATE_RANGE_DB_MAX 0.0f
#define OMX_GATE_RANGE_DB_DEFAULT -90.0f
#define OMX_GATE_KNEE_START_DB_MIN -80.0f
#define OMX_GATE_KNEE_START_DB_MAX 0.0f
#define OMX_GATE_KNEE_START_DB_DEFAULT -43.0f
#define OMX_GATE_KNEE_END_DB_MIN -80.0f
#define OMX_GATE_KNEE_END_DB_MAX 0.0f
#define OMX_GATE_KNEE_END_DB_DEFAULT -37.0f
#define OMX_GATE_ATTACK_MS_MIN 0.0f
#define OMX_GATE_ATTACK_MS_MAX 500.0f
#define OMX_GATE_ATTACK_MS_DEFAULT 1.0f
#define OMX_GATE_HOLD_MS_MIN 0.0f
#define OMX_GATE_HOLD_MS_MAX 2000.0f
#define OMX_GATE_HOLD_MS_DEFAULT 10.0f
#define OMX_GATE_RELEASE_MS_MIN 0.0f
#define OMX_GATE_RELEASE_MS_MAX 5000.0f
#define OMX_GATE_RELEASE_MS_DEFAULT 100.0f
#define OMX_GATE_HYSTERESIS_DB_MIN 0.0f
#define OMX_GATE_HYSTERESIS_DB_MAX 24.0f
#define OMX_GATE_HYSTERESIS_DB_DEFAULT 3.0f
#define OMX_GATE_RATIO_MIN 1.0f
#define OMX_GATE_RATIO_MAX 100.0f
#define OMX_GATE_RATIO_DEFAULT 16.0f

#define OMX_LIMITER_CEILING_DB_MIN -12.0f
#define OMX_LIMITER_CEILING_DB_MAX 0.0f
#define OMX_LIMITER_CEILING_DB_DEFAULT -1.0f
#define OMX_LIMITER_LOOKAHEAD_MS_MIN 0.5f
#define OMX_LIMITER_LOOKAHEAD_MS_MAX 5.0f
#define OMX_LIMITER_LOOKAHEAD_MS_DEFAULT 1.5f
#define OMX_LIMITER_RELEASE_MS_MIN 1.0f
#define OMX_LIMITER_RELEASE_MS_MAX 1000.0f
#define OMX_LIMITER_RELEASE_MS_DEFAULT 50.0f

#define OMX_PITCH_SEMITONES_MIN -12.0f
#define OMX_PITCH_SEMITONES_MAX 12.0f
#define OMX_PITCH_SEMITONES_DEFAULT 0.0f
#define OMX_PITCH_CENTS_MIN -50.0f
#define OMX_PITCH_CENTS_MAX 50.0f
#define OMX_PITCH_CENTS_DEFAULT 0.0f
#define OMX_PITCH_MIX_MIN 0.0f
#define OMX_PITCH_MIX_MAX 100.0f
#define OMX_PITCH_MIX_DEFAULT 100.0f

#define OMX_TRANSIENT_ATTACK_DB_MIN -24.0f
#define OMX_TRANSIENT_ATTACK_DB_MAX 24.0f
#define OMX_TRANSIENT_ATTACK_DB_DEFAULT 0.0f
#define OMX_TRANSIENT_SUSTAIN_DB_MIN -24.0f
#define OMX_TRANSIENT_SUSTAIN_DB_MAX 24.0f
#define OMX_TRANSIENT_SUSTAIN_DB_DEFAULT 0.0f
#define OMX_TRANSIENT_ATTACK_TIME_MS_MIN 2.0f
#define OMX_TRANSIENT_ATTACK_TIME_MS_MAX 50.0f
#define OMX_TRANSIENT_ATTACK_TIME_MS_DEFAULT 10.0f
#define OMX_TRANSIENT_SUSTAIN_TIME_MS_MIN 50.0f
#define OMX_TRANSIENT_SUSTAIN_TIME_MS_MAX 2000.0f
#define OMX_TRANSIENT_SUSTAIN_TIME_MS_DEFAULT 250.0f
#define OMX_TRANSIENT_OUTPUT_DB_MIN -24.0f
#define OMX_TRANSIENT_OUTPUT_DB_MAX 12.0f
#define OMX_TRANSIENT_OUTPUT_DB_DEFAULT 0.0f

/* The four coreLimits-sourced facts with a native meaning — pan, delay, reverb, drive
 * (CORE_LIMITS, control-bounds.ts; F7). Not every field here has a C-side literal to replace:
 * the reverb cut corners and the drive stage's five numerics are clamped only on the TS side
 * today (mix_reverb.h's own header comment: "there is no 20 kHz anywhere in the C"), so those
 * defines exist for completeness and for the day a native clamp is added, without yet being
 * read by a stage. */
#define OMX_PAN_PAN_MIN -1.0f
#define OMX_PAN_PAN_MAX 1.0f

#define OMX_DELAY_TIME_MS_MIN 0.0f
#define OMX_DELAY_TIME_MS_MAX 2000.0f
#define OMX_DELAY_TIME_MS_DEFAULT 300.0f

#define OMX_REVERB_LOWCUT_MIN 0.0f
#define OMX_REVERB_LOWCUT_MAX 20000.0f
#define OMX_REVERB_HIGHCUT_MIN 0.0f
#define OMX_REVERB_HIGHCUT_MAX 20000.0f

#define OMX_DRIVE_DRIVE_DB_MIN 0.0f
#define OMX_DRIVE_DRIVE_DB_MAX 36.0f
#define OMX_DRIVE_DRIVE_DB_DEFAULT 0.0f
#define OMX_DRIVE_CHARACTER_MIN -1.0f
#define OMX_DRIVE_CHARACTER_MAX 1.0f
#define OMX_DRIVE_CHARACTER_DEFAULT 0.0f
#define OMX_DRIVE_BAND_HZ_MIN 20.0f
#define OMX_DRIVE_BAND_HZ_MAX 20000.0f
#define OMX_DRIVE_BAND_HZ_DEFAULT 2000.0f
#define OMX_DRIVE_MIX_MIN 0.0f
#define OMX_DRIVE_MIX_MAX 100.0f
#define OMX_DRIVE_MIX_DEFAULT 100.0f
#define OMX_DRIVE_TRIM_DB_MIN -24.0f
#define OMX_DRIVE_TRIM_DB_MAX 12.0f
#define OMX_DRIVE_TRIM_DB_DEFAULT 0.0f

/* EVERY declared scalar and sheet leaf (packages/core/src/declared-scalars.ts over the core barrel
 * and @freemixer/declarations; dsp-primitives §7 the scalar door) — one block, sorted by macro,
 * named by nobody: a kernel's constants are its exports (ROTARY_*, TRANSIENT_*, PITCH_KERNEL,
 * PROGRAM_RELEASE, HOSTED_STAGE_LIMITS, ALLPASS/XOVER_LIMITS, the fdelay kernel's norm and order, …).
 * An integer value is an integer literal, any other a float literal. */
#define OMX_ALIGN_TRUST_COHERENCE 0.5f
#define OMX_ALLPASS_UNITY_TOLERANCE 0.0001f
#define OMX_BAND_F_MAX_CAP 20000
#define OMX_BAND_F_MIN 20
#define OMX_BAND_GATE_DB -60
#define OMX_BPM_MAX 300
#define OMX_BPM_MIN 30
#define OMX_BUS_INPUT_CAP 128
#define OMX_CENTRE_WINDOW_HALF_WIDTH 0.5f
#define OMX_CHAIN_INPUT -1
#define OMX_CHANNEL_CONFIG_SCHEMA_VERSION 1
#define OMX_CONTINUOUS 0
#define OMX_CONTRACT_VERSION_MAJOR 2
#define OMX_CONTRACT_VERSION_MINOR 9
#define OMX_CYCLE_FIXED_NS_176400 3394
#define OMX_CYCLE_FIXED_NS_192000 3394
#define OMX_CYCLE_FIXED_NS_44100 3621
#define OMX_CYCLE_FIXED_NS_48000 3621
#define OMX_CYCLE_FIXED_NS_88200 3463
#define OMX_CYCLE_FIXED_NS_96000 3463
#define OMX_DEEP_PLATEAU_FRAMES 20
#define OMX_DEESS_KNEE_DB 6
#define OMX_DEFAULT_BAND_HIGH_HZ 4000
#define OMX_DEFAULT_BAND_LOW_HZ 60
#define OMX_DEFAULT_FADE_FRACTION 0.02f
#define OMX_DEFAULT_FREQ_HZ 1000
#define OMX_DEFAULT_HEAD_AMP_GAIN_DB 32
#define OMX_DEFAULT_INPUT_CHANNELS 16
#define OMX_DEFAULT_LATENCY_BUDGET_MS_EFFECTS 60
#define OMX_DEFAULT_LATENCY_BUDGET_MS_MONITOR 5
#define OMX_DEFAULT_LATENCY_BUDGET_MS_PROGRAM 100
#define OMX_DEFAULT_LEVEL 0.5f
#define OMX_DEFAULT_PRESET_INPUTS 16
#define OMX_DEFAULT_PRESET_OUTPUTS 8
#define OMX_DEFAULT_THRESHOLDS_GROWTH_CONFIRM_FRAMES 2
#define OMX_DEFAULT_THRESHOLDS_GROWTH_MAX_DIP_DB 0.5f
#define OMX_DEFAULT_THRESHOLDS_GROWTH_MAX_SINGLE_FRAME_SHARE 0.5f
#define OMX_DEFAULT_THRESHOLDS_GROWTH_MIN_DB_PER_FRAME 0.8f
#define OMX_DEFAULT_THRESHOLDS_GROWTH_MIN_TOTAL_RISE_DB 6
#define OMX_DEFAULT_THRESHOLDS_PAPR_DB 18
#define OMX_DEFAULT_THRESHOLDS_PERSIST_FRAMES 5
#define OMX_DEFAULT_THRESHOLDS_PHPR_DB 9
#define OMX_DEFAULT_THRESHOLDS_PNPR_DB 12
#define OMX_DEFAULT_THRESHOLDS_PSHR_MIN_DB 10
#define OMX_DEFAULT_THRESHOLDS_SUB_CLEAN_FRAMES 5
#define OMX_DEFAULT_WEB_PORT 8080
#define OMX_DESK_GAIN_RANGE_MAX_DB 55
#define OMX_DESK_GAIN_RANGE_MIN_DB -24
#define OMX_DESK_GAIN_RANGE_STEP_DB 1
#define OMX_DETECTOR_OVERSAMPLE_AUTO_MS 0.5f
#define OMX_DETECTOR_OVERSAMPLE_LATENCY_SAMPLES 72
#define OMX_DRIVE_BIAS_MAX 0.7071067811865476f
#define OMX_EARLY_REFLECTION_FLOOR_DB -30
#define OMX_EARLY_REFLECTION_WINDOW_MS 80
#define OMX_EQ_DEFAULT_SAMPLE_RATE 48000
#define OMX_EQ_GAIN_LIMIT_DB 15
#define OMX_EQ_MAX_BANDS 24
#define OMX_FAMILY_COMP_RATIO_BOUNDS_BASS_MAX 4
#define OMX_FAMILY_COMP_RATIO_BOUNDS_BASS_MIN 3
#define OMX_FAMILY_COMP_RATIO_BOUNDS_BRASS_MAX 4
#define OMX_FAMILY_COMP_RATIO_BOUNDS_BRASS_MIN 3
#define OMX_FAMILY_COMP_RATIO_BOUNDS_DRUMS_MAX 6
#define OMX_FAMILY_COMP_RATIO_BOUNDS_DRUMS_MIN 4
#define OMX_FAMILY_COMP_RATIO_BOUNDS_GUITAR_MAX 3
#define OMX_FAMILY_COMP_RATIO_BOUNDS_GUITAR_MIN 2
#define OMX_FAMILY_COMP_RATIO_BOUNDS_KEYS_MAX 3
#define OMX_FAMILY_COMP_RATIO_BOUNDS_KEYS_MIN 2
#define OMX_FAMILY_COMP_RATIO_BOUNDS_PERCUSSION_MAX 4
#define OMX_FAMILY_COMP_RATIO_BOUNDS_PERCUSSION_MIN 2
#define OMX_FAMILY_COMP_RATIO_BOUNDS_PLAYBACK_MAX 12
#define OMX_FAMILY_COMP_RATIO_BOUNDS_PLAYBACK_MIN 8
#define OMX_FAMILY_COMP_RATIO_BOUNDS_STRINGS_MAX 3
#define OMX_FAMILY_COMP_RATIO_BOUNDS_STRINGS_MIN 2
#define OMX_FAMILY_COMP_RATIO_BOUNDS_VOCALS_MAX 3
#define OMX_FAMILY_COMP_RATIO_BOUNDS_VOCALS_MIN 2
#define OMX_FAMILY_COMP_RATIO_BOUNDS_WIND_MAX 4
#define OMX_FAMILY_COMP_RATIO_BOUNDS_WIND_MIN 3
#define OMX_FBS_DEFAULT_COOLDOWN_MINUTES 10
#define OMX_FBS_DEFAULT_HOLD_SECONDS 5
#define OMX_FBS_DEFAULT_MAX_AUTO_BANDS 6
#define OMX_FBS_DEFAULT_MERGE_CENTS 100
#define OMX_FBS_DEFAULT_NOTCH_Q 116
#define OMX_FBS_DEFAULT_SENSITIVITY 0
#define OMX_FBS_LIFT_RAMP_MS 3000
#define OMX_FBS_MAX_CUT_DB -24
#define OMX_FBS_MAX_NOTCH_DEPTH_DB 18
#define OMX_FBS_RECLAMP_BACKOFF_CAP 3
#define OMX_FBS_RECLAMP_DEEPEN_DB 3
#define OMX_FBS_RELEASE_DONE_DB 1
#define OMX_FBS_RELEASE_DWELL_MS 8000
#define OMX_FBS_RELEASE_RATIO 0.6666666666666666f
#define OMX_FBS_RING_HZ_MAX 16000
#define OMX_FBS_RING_HZ_MIN 60
#define OMX_FDELAY_MOD_READ_ORDER 3
#define OMX_FDELAY_READ_L1_NORM 1.25f
#define OMX_GATE_KEY_VOICE_BAND_HP_HZ 120
#define OMX_GATE_KEY_VOICE_BAND_LP_HZ 8000
#define OMX_GATE_RANGE_FLOOR_DB -90
#define OMX_GEQ_BANDS 31
#define OMX_GEQ_BAND_Q 4.3f
#define OMX_GROWTH_CONFIRM_FRAMES 2
#define OMX_GROWTH_MAX_DIP_DB 0.5f
#define OMX_GROWTH_MAX_SINGLE_FRAME_SHARE 0.5f
#define OMX_GROWTH_MIN_DB_PER_FRAME 0.8f
#define OMX_GROWTH_MIN_TOTAL_RISE_DB 6
#define OMX_GROWTH_WINDOW_FRAMES 5
#define OMX_HEAD_AMP_GAIN_MAX_DB 55
#define OMX_HEAD_AMP_GAIN_MIN_DB 0
#define OMX_HOSTED_STAGE_CLAMP_DBFS 24
#define OMX_HOSTED_STAGE_EVENTS_PER_BLOCK 64
#define OMX_HOSTED_STAGE_NON_FINITE_STRIKES 3
#define OMX_HOSTED_STAGE_PARAM_QUEUE_DEPTH 256
#define OMX_HOSTED_STAGE_WARMUP_BLOCKS 64
#define OMX_HOSTED_STAGE_WARMUP_LEVEL_DBFS -6
#define OMX_HRP_BAND_Q 5
#define OMX_HRP_COLLISION_CENTS 100
#define OMX_HRP_DEFAULT_MAX_AUTO_BANDS 8
#define OMX_HRP_EXCESS_THRESHOLD_DB 3
#define OMX_HRP_FAMILY_SEARCH_BASS_F0_MAX_HZ 400
#define OMX_HRP_FAMILY_SEARCH_BASS_F0_MIN_HZ 25
#define OMX_HRP_FAMILY_SEARCH_BASS_MAX_VOICES 2
#define OMX_HRP_FAMILY_SEARCH_BRASS_F0_MAX_HZ 1400
#define OMX_HRP_FAMILY_SEARCH_BRASS_F0_MIN_HZ 40
#define OMX_HRP_FAMILY_SEARCH_BRASS_MAX_VOICES 2
#define OMX_HRP_FAMILY_SEARCH_DRUMS_F0_MAX_HZ 400
#define OMX_HRP_FAMILY_SEARCH_DRUMS_F0_MIN_HZ 35
#define OMX_HRP_FAMILY_SEARCH_DRUMS_MAX_VOICES 1
#define OMX_HRP_FAMILY_SEARCH_GUITAR_F0_MAX_HZ 1400
#define OMX_HRP_FAMILY_SEARCH_GUITAR_F0_MIN_HZ 60
#define OMX_HRP_FAMILY_SEARCH_GUITAR_MAX_VOICES 6
#define OMX_HRP_FAMILY_SEARCH_KEYS_F0_MAX_HZ 4200
#define OMX_HRP_FAMILY_SEARCH_KEYS_F0_MIN_HZ 27.5f
#define OMX_HRP_FAMILY_SEARCH_KEYS_MAX_VOICES 8
#define OMX_HRP_FAMILY_SEARCH_PERCUSSION_F0_MAX_HZ 1200
#define OMX_HRP_FAMILY_SEARCH_PERCUSSION_F0_MIN_HZ 60
#define OMX_HRP_FAMILY_SEARCH_PERCUSSION_MAX_VOICES 1
#define OMX_HRP_FAMILY_SEARCH_PLAYBACK_F0_MAX_HZ 2100
#define OMX_HRP_FAMILY_SEARCH_PLAYBACK_F0_MIN_HZ 25
#define OMX_HRP_FAMILY_SEARCH_PLAYBACK_MAX_VOICES 8
#define OMX_HRP_FAMILY_SEARCH_STRINGS_F0_MAX_HZ 2800
#define OMX_HRP_FAMILY_SEARCH_STRINGS_F0_MIN_HZ 40
#define OMX_HRP_FAMILY_SEARCH_STRINGS_MAX_VOICES 8
#define OMX_HRP_FAMILY_SEARCH_VOCALS_F0_MAX_HZ 1200
#define OMX_HRP_FAMILY_SEARCH_VOCALS_F0_MIN_HZ 80
#define OMX_HRP_FAMILY_SEARCH_VOCALS_MAX_VOICES 2
#define OMX_HRP_FAMILY_SEARCH_WIND_F0_MAX_HZ 2600
#define OMX_HRP_FAMILY_SEARCH_WIND_F0_MIN_HZ 55
#define OMX_HRP_FAMILY_SEARCH_WIND_MAX_VOICES 2
#define OMX_HRP_GAIN_STEP_DB 2
#define OMX_HRP_HARMONIC_COUNT 12
#define OMX_HRP_MAX_BOOST_DB 0
#define OMX_HRP_MAX_CUT_DB 6
#define OMX_HRP_MAX_VOICES 8
#define OMX_HRP_TIER_CROSSOVER_HZ 1000
#define OMX_LANE_WALK_NS_176400 3394
#define OMX_LANE_WALK_NS_192000 3394
#define OMX_LANE_WALK_NS_44100 3621
#define OMX_LANE_WALK_NS_48000 3621
#define OMX_LANE_WALK_NS_88200 3463
#define OMX_LANE_WALK_NS_96000 3463
#define OMX_MAX_FREQ_HZ 20000
#define OMX_MAX_INPUT_CHANNELS 128
#define OMX_MAX_SYNC_DIVISION 16
#define OMX_METER_FLOOR_DB -60
#define OMX_METER_RELEASE_PER_FRAME 0.012f
#define OMX_METER_STEP_HYSTERESIS 0.25f
#define OMX_MIN_FRAMES 4
#define OMX_MIN_FREQ_HZ 20
#define OMX_MIN_INPUT_CHANNELS 8
#define OMX_MIN_SYNC_DIVISION 0.0625f
#define OMX_MONO_FOLD_COEF 0.5f
#define OMX_NATIVE_INSERT_STAGE 9
#define OMX_NATIVE_STAGE_ID_CHORUS 6
#define OMX_NATIVE_STAGE_ID_DELAY 4
#define OMX_NATIVE_STAGE_ID_DE_ESSER 8
#define OMX_NATIVE_STAGE_ID_DRIVE 3
#define OMX_NATIVE_STAGE_ID_DYNAMICS 2
#define OMX_NATIVE_STAGE_ID_EQ 1
#define OMX_NATIVE_STAGE_ID_FLANGER 7
#define OMX_NATIVE_STAGE_ID_GATE 0
#define OMX_NATIVE_STAGE_ID_REVERB 5
#define OMX_NO_BUSES_AUX 0
#define OMX_NO_BUSES_DCA 0
#define OMX_NO_BUSES_FX_RETURN 0
#define OMX_NO_BUSES_GROUP 0
#define OMX_NO_BUSES_MAIN 0
#define OMX_NO_BUSES_MATRIX 0
#define OMX_NO_BUSES_MIX_MINUS 0
#define OMX_OPERATOR_EQ_BANDS_RESERVE 9
#define OMX_PATCH_SCHEMA_VERSION 1
#define OMX_PITCH_PREFILTER_CEILING_HZ 20000
#define OMX_PITCH_PREFILTER_Q 0.7071067811865476f
#define OMX_PITCH_WINDOW_MS 40
#define OMX_PROGRAM_RELEASE_CHARGE_MS 1000
#define OMX_PROGRAM_RELEASE_DISCHARGE_MS 5000
#define OMX_PROGRAM_RELEASE_PROFILES_OPTO_FAST_MS 70
#define OMX_PROGRAM_RELEASE_PROFILES_OPTO_SHARE 0.5f
#define OMX_PROGRAM_RELEASE_PROFILES_OPTO_SLOW_MAX_MS 1100
#define OMX_PROGRAM_RELEASE_PROFILES_OPTO_SLOW_MIN_MS 110
#define OMX_PSHR_MIN_DB 10
#define OMX_REAC_AUDIO_FABRIC_CEILING 39
#define OMX_REAC_AUDIO_FABRIC_SLOTS 40
#define OMX_REAC_CFG_RATE_44100 44100
#define OMX_REAC_CFG_RATE_48000 48000
#define OMX_REAC_CFG_RATE_96000 96000
#define OMX_REAC_CFG_RATE_COUNT 3
#define OMX_REAC_CFG_ROLE_MASTER 0
#define OMX_REAC_CFG_ROLE_SLAVE 1
#define OMX_REAC_HEADAMP_CEILING 47
#define OMX_REAC_HEADAMP_RING 49
#define OMX_REAC_HEADAMP_SLOTS 48
#define OMX_REAC_HEAD_AMP_GAIN_RANGE_MAX_DB 55
#define OMX_REAC_HEAD_AMP_GAIN_RANGE_MIN_DB 0
#define OMX_REAC_HEAD_AMP_GAIN_RANGE_STEP_DB 1
#define OMX_ROOM_MODE_BAND_HIGH_HZ 300
#define OMX_ROOM_MODE_BAND_LOW_HZ 20
#define OMX_ROOM_MODE_MAX_CUT_DB 15
#define OMX_ROOM_MODE_MIN_ABOVE_MEDIAN_DB 6
#define OMX_ROOM_MODE_MIN_POSITIONS 2
#define OMX_ROTARY_BASE_MS 0.1f
#define OMX_ROTARY_CROSSOVER_HZ 800
#define OMX_ROTARY_DRUM_ACCEL_MS 1700
#define OMX_ROTARY_DRUM_AM 0.3f
#define OMX_ROTARY_DRUM_DECEL_MS 1800
#define OMX_ROTARY_DRUM_DOPPLER_MS 0.29f
#define OMX_ROTARY_HORN_ACCEL_MS 330
#define OMX_ROTARY_HORN_AM 0.5f
#define OMX_ROTARY_HORN_DECEL_MS 500
#define OMX_ROTARY_HORN_DOPPLER_MS 0.44f
#define OMX_ROTARY_RING_FLOATS 256
#define OMX_ROTARY_STOP_EPS 0.0001f
#define OMX_RTA_FFT_SIZE_MAX 32768
#define OMX_RTA_TAP_GATE_DB -60
#define OMX_RTA_TARGET_BIN_HZ 5.9f
#define OMX_RT_ADMISSION_CEILING_RATIO 0.6f
#define OMX_RT_CAPACITY_TOLERANCE 0.1f
#define OMX_RT_HARD_TARGET_QUANTUM 128
#define OMX_RT_HARD_TARGET_RATE 192000
#define OMX_RT_HEADROOM_REFUSE_RATIO 0.8f
#define OMX_RT_HEADROOM_WARN_RATIO 0.6f
#define OMX_RT_PREDICTION_TOLERANCE 0.1f
#define OMX_RT_SPLIT_ECORE_WEIGHT_SEED 0.5f
#define OMX_RT_STAGE_MAX_FACTOR 2
#define OMX_SCENE_SCHEMA_VERSION 1
#define OMX_SENS_VALUE_MAX 55
#define OMX_SENS_VALUE_MIN 0
#define OMX_SESSION_SCHEMA_VERSION 1
#define OMX_SPEAKER_ALIGN_BAND_HIGH_HZ 4000
#define OMX_SPEAKER_ALIGN_BAND_LOW_HZ 125
#define OMX_SPEED_OF_SOUND_M_S 343
#define OMX_STAGE_COST_NS_PER_SAMPLE_CHORUS_176400 27.5f
#define OMX_STAGE_COST_NS_PER_SAMPLE_CHORUS_192000 27.5f
#define OMX_STAGE_COST_NS_PER_SAMPLE_CHORUS_44100 28.8f
#define OMX_STAGE_COST_NS_PER_SAMPLE_CHORUS_48000 28.8f
#define OMX_STAGE_COST_NS_PER_SAMPLE_CHORUS_88200 28.2f
#define OMX_STAGE_COST_NS_PER_SAMPLE_CHORUS_96000 28.2f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DELAY_176400 27.5f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DELAY_192000 27.5f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DELAY_44100 28.8f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DELAY_48000 28.8f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DELAY_88200 28.2f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DELAY_96000 28.2f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DE_ESSER_176400 27.5f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DE_ESSER_192000 27.5f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DE_ESSER_44100 28.8f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DE_ESSER_48000 28.8f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DE_ESSER_88200 28.2f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DE_ESSER_96000 28.2f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DRIVE_176400 27.5f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DRIVE_192000 27.5f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DRIVE_44100 28.8f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DRIVE_48000 28.8f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DRIVE_88200 28.2f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DRIVE_96000 28.2f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DYNAMICS_176400 27.5f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DYNAMICS_192000 27.5f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DYNAMICS_44100 28.8f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DYNAMICS_48000 28.8f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DYNAMICS_88200 28.2f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DYNAMICS_96000 28.2f
#define OMX_STAGE_COST_NS_PER_SAMPLE_EQ_176400 27.5f
#define OMX_STAGE_COST_NS_PER_SAMPLE_EQ_192000 27.5f
#define OMX_STAGE_COST_NS_PER_SAMPLE_EQ_44100 28.8f
#define OMX_STAGE_COST_NS_PER_SAMPLE_EQ_48000 28.8f
#define OMX_STAGE_COST_NS_PER_SAMPLE_EQ_88200 28.2f
#define OMX_STAGE_COST_NS_PER_SAMPLE_EQ_96000 28.2f
#define OMX_STAGE_COST_NS_PER_SAMPLE_FLANGER_176400 27.5f
#define OMX_STAGE_COST_NS_PER_SAMPLE_FLANGER_192000 27.5f
#define OMX_STAGE_COST_NS_PER_SAMPLE_FLANGER_44100 28.8f
#define OMX_STAGE_COST_NS_PER_SAMPLE_FLANGER_48000 28.8f
#define OMX_STAGE_COST_NS_PER_SAMPLE_FLANGER_88200 28.2f
#define OMX_STAGE_COST_NS_PER_SAMPLE_FLANGER_96000 28.2f
#define OMX_STAGE_COST_NS_PER_SAMPLE_GATE_176400 27.5f
#define OMX_STAGE_COST_NS_PER_SAMPLE_GATE_192000 27.5f
#define OMX_STAGE_COST_NS_PER_SAMPLE_GATE_44100 28.8f
#define OMX_STAGE_COST_NS_PER_SAMPLE_GATE_48000 28.8f
#define OMX_STAGE_COST_NS_PER_SAMPLE_GATE_88200 28.2f
#define OMX_STAGE_COST_NS_PER_SAMPLE_GATE_96000 28.2f
#define OMX_STAGE_COST_NS_PER_SAMPLE_REVERB_176400 27.5f
#define OMX_STAGE_COST_NS_PER_SAMPLE_REVERB_192000 27.5f
#define OMX_STAGE_COST_NS_PER_SAMPLE_REVERB_44100 28.8f
#define OMX_STAGE_COST_NS_PER_SAMPLE_REVERB_48000 28.8f
#define OMX_STAGE_COST_NS_PER_SAMPLE_REVERB_88200 28.2f
#define OMX_STAGE_COST_NS_PER_SAMPLE_REVERB_96000 28.2f
#define OMX_STRIP_QUANTUM 4
#define OMX_SUBHARMONIC_RADIUS_BINS 2
#define OMX_SURFACE_BANK_WIDTH 8
#define OMX_T20_LOWER_DB -25
#define OMX_T20_UPPER_DB -5
#define OMX_TAKE_RENDER_SCHEMA_VERSION 1
#define OMX_TAKE_REVERSE_RENDER_SCHEMA_VERSION 1
#define OMX_TAKE_SCHEMA_VERSION 1
#define OMX_TAPER_FLOOR_DB -90
#define OMX_TAP_AT_CHAIN_INPUT -1
#define OMX_TAP_RESET_MS 2000
#define OMX_TAP_WINDOW 4
#define OMX_TIER_CROSSOVER_HZ 300
#define OMX_TRANSIENT_FAST_ATTACK_MS 0.5f
#define OMX_TRANSIENT_FAST_RELEASE_MS 20
#define OMX_TRANSIENT_FLOOR_LIN 0.00001f
#define OMX_TRANSIENT_REF_DB 6
#define OMX_TRIM_RANGE_MAX_DB 24
#define OMX_TRIM_RANGE_MIN_DB -24
#define OMX_TRIM_RANGE_STEP_DB 0.1f
#define OMX_UNITY_POSITION 0.75f
#define OMX_XOVER_LR2_SECTION_Q 0.5f
#define OMX_XOVER_LR4_SECTION_Q 0.7071067811865476f
#define OMX_XOVER_PARTITION_TOLERANCE 0.00001f

/* The CLAP host object's extension ids (packages/plugin-qualify/src/hosting-suitability.ts,
 * OMX_CLAP_HOST_EXTENSIONS; 2026-09-26-clap-hosting-path.md §5) — read by mix_clap_host.c. */
#define OMX_CLAP_HOST_EXTENSION_COUNT 6u
#define OMX_CLAP_HOST_EXTENSIONS_INIT { "clap.log", "clap.thread-check", "clap.latency", "clap.params", "clap.audio-ports", "clap.state", NULL }

#endif /* OMX_CONTRACT_LIMITS_H */

/* The sample rates the console declares (core's STANDARD_SAMPLE_RATES, row-codecs.ts): the set a
 * contract's rate-is-declared precondition accepts, through omx_rate_is_declared(), and the grid a
 * native tool iterates. Guarded on its own so a tool built against a pinned copy of this header
 * (lv2-inprocess-pin.sh) can include this tree's copy after it and gain the rates without mixing
 * the pin's limits. */
#ifndef OMX_DECLARED_RATE_COUNT
#define OMX_DECLARED_RATE_COUNT 6u
static const float OMX_DECLARED_RATES[OMX_DECLARED_RATE_COUNT] = { 44100.0f, 48000.0f, 88200.0f, 96000.0f, 176400.0f, 192000.0f };
/* The declared rates that are whole multiples of `base` (a tool's default grid: the 48 kHz family),
 * in declaration order, at most `cap` of them; returns how many were written to `out`. */
static inline int omx_declared_rates_multiple_of(unsigned base, int *out, int cap) {
  int n = 0;
  for (unsigned k = 0; k < OMX_DECLARED_RATE_COUNT && n < cap; k++)
    if ((unsigned)OMX_DECLARED_RATES[k] % base == 0) out[n++] = (int)OMX_DECLARED_RATES[k];
  return n;
}
#endif
