#ifndef OMX_CONTRACT_LIMITS_H
#define OMX_CONTRACT_LIMITS_H
/*
 * GENERATED — DO NOT EDIT BY HAND.
 * Produced by harness/contract-limits-gen.mjs from packages/core/src/channel-contract.ts's
 * `laws` column (R-056), every table packages/core/src/native-limit-tables.ts's registry
 * holds, packages/core/src/control-bounds.ts's CORE_LIMITS for the pan/delay/reverb/drive
 * facts, EVERY declared scalar and all-number sheet packages/core/src/declared-scalars.ts
 * discovers over the core barrel and @freemixer/declarations (dsp-primitives §7), and
 * packages/core/src/row-codecs.ts's STANDARD_SAMPLE_RATES. Regenerate:
 * `node harness/contract-limits-gen.mjs`, then commit the result — see this file's own
 * generator for why it is committed rather than gitignored.
 *
 * A C contract (OMX_PRE/OMX_POST/OMX_INVARIANT) reads a limit from HERE, never a literal:
 * packages/server/src/contract-limits-generated-conformance.test.ts refuses both a stale
 * header and a C literal that duplicates a number this file already declares.
 */

/* The closed law vocabulary (core's LAW_KINDS, fact-declaration.ts) — one member per law. */
typedef enum {
  OMX_LAW_NO_GAIN_ADDED = 0,
  OMX_LAW_OUTPUT_LE_INPUT_PLUS,
  OMX_LAW_UNITY_AT_DEFAULT,
  OMX_LAW_DELAYED_COPY,
  OMX_LAW_BYPASS_IDENTITY,
  OMX_LAW_TAIL_DECAYS,
  OMX_LAW_CONSTANT_POWER_PAN,
  OMX_LAW_LINEAR_SUM,
  OMX_LAW_FINITE,
  OMX_LAW_NO_DENORMAL_STATE,
} omx_contract_law_t;

/* Per-stage law lists, one per channel fact whose row declares `laws` — the SAME array
 * harness/contracts-scaffold.mjs's applier and the MCP contract_laws tool read; a stage's
 * OMX_POST tokens implement one or more of these, never a second spelling of the law. */
static const omx_contract_law_t OMX_STAGE_LAWS_PAN[] = { OMX_LAW_FINITE, OMX_LAW_CONSTANT_POWER_PAN };
#define OMX_STAGE_LAWS_PAN_COUNT 2

static const omx_contract_law_t OMX_STAGE_LAWS_EQ[] = { OMX_LAW_FINITE, OMX_LAW_NO_DENORMAL_STATE, OMX_LAW_BYPASS_IDENTITY };
#define OMX_STAGE_LAWS_EQ_COUNT 3

static const omx_contract_law_t OMX_STAGE_LAWS_GATE[] = { OMX_LAW_FINITE, OMX_LAW_NO_DENORMAL_STATE, OMX_LAW_BYPASS_IDENTITY, OMX_LAW_NO_GAIN_ADDED, OMX_LAW_UNITY_AT_DEFAULT };
#define OMX_STAGE_LAWS_GATE_COUNT 5

static const omx_contract_law_t OMX_STAGE_LAWS_DYNAMICS[] = { OMX_LAW_FINITE, OMX_LAW_NO_DENORMAL_STATE, OMX_LAW_BYPASS_IDENTITY, OMX_LAW_OUTPUT_LE_INPUT_PLUS, OMX_LAW_UNITY_AT_DEFAULT };
#define OMX_STAGE_LAWS_DYNAMICS_COUNT 5

static const omx_contract_law_t OMX_STAGE_LAWS_DELAY[] = { OMX_LAW_FINITE, OMX_LAW_BYPASS_IDENTITY, OMX_LAW_DELAYED_COPY };
#define OMX_STAGE_LAWS_DELAY_COUNT 3

static const omx_contract_law_t OMX_STAGE_LAWS_REVERB[] = { OMX_LAW_FINITE, OMX_LAW_NO_DENORMAL_STATE, OMX_LAW_BYPASS_IDENTITY, OMX_LAW_TAIL_DECAYS };
#define OMX_STAGE_LAWS_REVERB_COUNT 4

static const omx_contract_law_t OMX_STAGE_LAWS_DRIVE[] = { OMX_LAW_FINITE, OMX_LAW_BYPASS_IDENTITY, OMX_LAW_UNITY_AT_DEFAULT };
#define OMX_STAGE_LAWS_DRIVE_COUNT 3

static const omx_contract_law_t OMX_STAGE_LAWS_DEESSER[] = { OMX_LAW_FINITE, OMX_LAW_NO_DENORMAL_STATE, OMX_LAW_BYPASS_IDENTITY, OMX_LAW_NO_GAIN_ADDED };
#define OMX_STAGE_LAWS_DEESSER_COUNT 4

static const omx_contract_law_t OMX_STAGE_LAWS_CHORUS[] = { OMX_LAW_FINITE, OMX_LAW_BYPASS_IDENTITY };
#define OMX_STAGE_LAWS_CHORUS_COUNT 2

static const omx_contract_law_t OMX_STAGE_LAWS_FLANGER[] = { OMX_LAW_FINITE, OMX_LAW_NO_DENORMAL_STATE, OMX_LAW_BYPASS_IDENTITY };
#define OMX_STAGE_LAWS_FLANGER_COUNT 3

static const omx_contract_law_t OMX_STAGE_LAWS_LIMITER[] = { OMX_LAW_FINITE, OMX_LAW_BYPASS_IDENTITY };
#define OMX_STAGE_LAWS_LIMITER_COUNT 2

static const omx_contract_law_t OMX_STAGE_LAWS_TOMAIN[] = { OMX_LAW_FINITE, OMX_LAW_LINEAR_SUM };
#define OMX_STAGE_LAWS_TOMAIN_COUNT 2

/* Per-parameter numeric travel, one block per table registered in
 * packages/core/src/native-limit-tables.ts (GATE/COMP today; a kernel that registers a table
 * lands here because it is REGISTERED, not because this generator names it). */
#define OMX_COMP_THRESHOLD_DB_MIN -60.0f
#define OMX_COMP_THRESHOLD_DB_MAX 0.0f
#define OMX_COMP_THRESHOLD_DB_DEFAULT -18.0f
#define OMX_COMP_RATIO_MIN 1.0f
#define OMX_COMP_RATIO_MAX 20.0f
#define OMX_COMP_RATIO_DEFAULT 4.0f
#define OMX_COMP_KNEE_DB_MIN 0.0f
#define OMX_COMP_KNEE_DB_MAX 24.0f
#define OMX_COMP_KNEE_DB_DEFAULT 6.0f
#define OMX_COMP_ATTACK_MS_MIN 0.1f
#define OMX_COMP_ATTACK_MS_MAX 100.0f
#define OMX_COMP_ATTACK_MS_DEFAULT 5.0f
#define OMX_COMP_RELEASE_MS_MIN 5.0f
#define OMX_COMP_RELEASE_MS_MAX 3000.0f
#define OMX_COMP_RELEASE_MS_DEFAULT 200.0f
#define OMX_COMP_MAKEUP_DB_MIN 0.0f
#define OMX_COMP_MAKEUP_DB_MAX 24.0f
#define OMX_COMP_MAKEUP_DB_DEFAULT 0.0f
#define OMX_COMP_MIX_PCT_MIN 0.0f
#define OMX_COMP_MIX_PCT_MAX 100.0f
#define OMX_COMP_MIX_PCT_DEFAULT 100.0f

#define OMX_GATE_THRESHOLD_DB_MIN -80.0f
#define OMX_GATE_THRESHOLD_DB_MAX 0.0f
#define OMX_GATE_THRESHOLD_DB_DEFAULT -40.0f
#define OMX_GATE_RANGE_DB_MIN -90.0f
#define OMX_GATE_RANGE_DB_MAX 0.0f
#define OMX_GATE_RANGE_DB_DEFAULT -90.0f
#define OMX_GATE_KNEE_START_DB_MIN -80.0f
#define OMX_GATE_KNEE_START_DB_MAX 0.0f
#define OMX_GATE_KNEE_START_DB_DEFAULT -43.0f
#define OMX_GATE_KNEE_END_DB_MIN -80.0f
#define OMX_GATE_KNEE_END_DB_MAX 0.0f
#define OMX_GATE_KNEE_END_DB_DEFAULT -37.0f
#define OMX_GATE_ATTACK_MS_MIN 0.0f
#define OMX_GATE_ATTACK_MS_MAX 500.0f
#define OMX_GATE_ATTACK_MS_DEFAULT 1.0f
#define OMX_GATE_HOLD_MS_MIN 0.0f
#define OMX_GATE_HOLD_MS_MAX 2000.0f
#define OMX_GATE_HOLD_MS_DEFAULT 10.0f
#define OMX_GATE_RELEASE_MS_MIN 0.0f
#define OMX_GATE_RELEASE_MS_MAX 5000.0f
#define OMX_GATE_RELEASE_MS_DEFAULT 100.0f
#define OMX_GATE_HYSTERESIS_DB_MIN 0.0f
#define OMX_GATE_HYSTERESIS_DB_MAX 24.0f
#define OMX_GATE_HYSTERESIS_DB_DEFAULT 3.0f
#define OMX_GATE_RATIO_MIN 1.0f
#define OMX_GATE_RATIO_MAX 100.0f
#define OMX_GATE_RATIO_DEFAULT 16.0f

#define OMX_LIMITER_CEILING_DB_MIN -12.0f
#define OMX_LIMITER_CEILING_DB_MAX 0.0f
#define OMX_LIMITER_CEILING_DB_DEFAULT -1.0f
#define OMX_LIMITER_LOOKAHEAD_MS_MIN 0.5f
#define OMX_LIMITER_LOOKAHEAD_MS_MAX 5.0f
#define OMX_LIMITER_LOOKAHEAD_MS_DEFAULT 1.5f
#define OMX_LIMITER_RELEASE_MS_MIN 1.0f
#define OMX_LIMITER_RELEASE_MS_MAX 1000.0f
#define OMX_LIMITER_RELEASE_MS_DEFAULT 50.0f

#define OMX_PITCH_SEMITONES_MIN -12.0f
#define OMX_PITCH_SEMITONES_MAX 12.0f
#define OMX_PITCH_SEMITONES_DEFAULT 0.0f
#define OMX_PITCH_CENTS_MIN -50.0f
#define OMX_PITCH_CENTS_MAX 50.0f
#define OMX_PITCH_CENTS_DEFAULT 0.0f
#define OMX_PITCH_MIX_MIN 0.0f
#define OMX_PITCH_MIX_MAX 100.0f
#define OMX_PITCH_MIX_DEFAULT 100.0f

#define OMX_TRANSIENT_ATTACK_DB_MIN -24.0f
#define OMX_TRANSIENT_ATTACK_DB_MAX 24.0f
#define OMX_TRANSIENT_ATTACK_DB_DEFAULT 0.0f
#define OMX_TRANSIENT_SUSTAIN_DB_MIN -24.0f
#define OMX_TRANSIENT_SUSTAIN_DB_MAX 24.0f
#define OMX_TRANSIENT_SUSTAIN_DB_DEFAULT 0.0f
#define OMX_TRANSIENT_ATTACK_TIME_MS_MIN 2.0f
#define OMX_TRANSIENT_ATTACK_TIME_MS_MAX 50.0f
#define OMX_TRANSIENT_ATTACK_TIME_MS_DEFAULT 10.0f
#define OMX_TRANSIENT_SUSTAIN_TIME_MS_MIN 50.0f
#define OMX_TRANSIENT_SUSTAIN_TIME_MS_MAX 2000.0f
#define OMX_TRANSIENT_SUSTAIN_TIME_MS_DEFAULT 250.0f
#define OMX_TRANSIENT_OUTPUT_DB_MIN -24.0f
#define OMX_TRANSIENT_OUTPUT_DB_MAX 12.0f
#define OMX_TRANSIENT_OUTPUT_DB_DEFAULT 0.0f

/* The four coreLimits-sourced facts with a native meaning — pan, delay, reverb, drive
 * (CORE_LIMITS, control-bounds.ts; F7). Not every field here has a C-side literal to replace:
 * the reverb cut corners and the drive stage's five numerics are clamped only on the TS side
 * today (mix_reverb.h's own header comment: "there is no 20 kHz anywhere in the C"), so those
 * defines exist for completeness and for the day a native clamp is added, without yet being
 * read by a stage. */
#define OMX_PAN_PAN_MIN -1.0f
#define OMX_PAN_PAN_MAX 1.0f

#define OMX_DELAY_TIME_MS_MIN 0.0f
#define OMX_DELAY_TIME_MS_MAX 2000.0f
#define OMX_DELAY_TIME_MS_DEFAULT 300.0f

#define OMX_REVERB_LOWCUT_MIN 0.0f
#define OMX_REVERB_LOWCUT_MAX 20000.0f
#define OMX_REVERB_HIGHCUT_MIN 0.0f
#define OMX_REVERB_HIGHCUT_MAX 20000.0f

#define OMX_DRIVE_DRIVE_DB_MIN 0.0f
#define OMX_DRIVE_DRIVE_DB_MAX 36.0f
#define OMX_DRIVE_DRIVE_DB_DEFAULT 0.0f
#define OMX_DRIVE_CHARACTER_MIN -1.0f
#define OMX_DRIVE_CHARACTER_MAX 1.0f
#define OMX_DRIVE_CHARACTER_DEFAULT 0.0f
#define OMX_DRIVE_BAND_HZ_MIN 20.0f
#define OMX_DRIVE_BAND_HZ_MAX 20000.0f
#define OMX_DRIVE_BAND_HZ_DEFAULT 2000.0f
#define OMX_DRIVE_MIX_MIN 0.0f
#define OMX_DRIVE_MIX_MAX 100.0f
#define OMX_DRIVE_MIX_DEFAULT 100.0f
#define OMX_DRIVE_TRIM_DB_MIN -24.0f
#define OMX_DRIVE_TRIM_DB_MAX 12.0f
#define OMX_DRIVE_TRIM_DB_DEFAULT 0.0f

/* EVERY declared scalar and sheet leaf (packages/core/src/declared-scalars.ts over the core barrel
 * and @freemixer/declarations; dsp-primitives §7 the scalar door) — one block, sorted by macro,
 * named by nobody: a kernel's constants are its exports (ROTARY_*, TRANSIENT_*, PITCH_KERNEL,
 * PROGRAM_RELEASE, HOSTED_STAGE_LIMITS, ALLPASS/XOVER_LIMITS, the fdelay kernel's norm and order, …).
 * An integer value is an integer literal, any other a float literal AND its OMX_<macro>_DOUBLE spelling. */
#define OMX_ALIGN_TRUST_COHERENCE 0.5f
#define OMX_ALIGN_TRUST_COHERENCE_DOUBLE 0.5
#define OMX_ALLPASS_UNITY_TOLERANCE 0.0001f
#define OMX_ALLPASS_UNITY_TOLERANCE_DOUBLE 0.0001
#define OMX_BAND_F_MAX_CAP 20000
#define OMX_BAND_F_MIN 20
#define OMX_BAND_GATE_DB -60
#define OMX_BPM_MAX 300
#define OMX_BPM_MIN 30
#define OMX_BUS_INPUT_CAP 128
#define OMX_CENTRE_WINDOW_HALF_WIDTH 0.5f
#define OMX_CENTRE_WINDOW_HALF_WIDTH_DOUBLE 0.5
#define OMX_CHAIN_INPUT -1
#define OMX_CHANNEL_CONFIG_SCHEMA_VERSION 1
#define OMX_CONTINUOUS 0
#define OMX_CONTRACT_VERSION_MAJOR 2
#define OMX_CONTRACT_VERSION_MINOR 11
#define OMX_CYCLE_FIXED_NS_176400 9382.1f
#define OMX_CYCLE_FIXED_NS_176400_DOUBLE 9382.1
#define OMX_CYCLE_FIXED_NS_192000 9382.1f
#define OMX_CYCLE_FIXED_NS_192000_DOUBLE 9382.1
#define OMX_CYCLE_FIXED_NS_44100 9309.2f
#define OMX_CYCLE_FIXED_NS_44100_DOUBLE 9309.2
#define OMX_CYCLE_FIXED_NS_48000 9309.2f
#define OMX_CYCLE_FIXED_NS_48000_DOUBLE 9309.2
#define OMX_CYCLE_FIXED_NS_88200 9309.2f
#define OMX_CYCLE_FIXED_NS_88200_DOUBLE 9309.2
#define OMX_CYCLE_FIXED_NS_96000 9309.2f
#define OMX_CYCLE_FIXED_NS_96000_DOUBLE 9309.2
#define OMX_DEEP_PLATEAU_FRAMES 20
#define OMX_DEESS_KNEE_DB 6
#define OMX_DEFAULT_BAND_HIGH_HZ 4000
#define OMX_DEFAULT_BAND_LOW_HZ 60
#define OMX_DEFAULT_FADE_FRACTION 0.02f
#define OMX_DEFAULT_FADE_FRACTION_DOUBLE 0.02
#define OMX_DEFAULT_FREQ_HZ 1000
#define OMX_DEFAULT_HEAD_AMP_GAIN_DB 32
#define OMX_DEFAULT_INPUT_CHANNELS 16
#define OMX_DEFAULT_LATENCY_BUDGET_MS_EFFECTS 60
#define OMX_DEFAULT_LATENCY_BUDGET_MS_MONITOR 5
#define OMX_DEFAULT_LATENCY_BUDGET_MS_PROGRAM 100
#define OMX_DEFAULT_LEVEL 0.5f
#define OMX_DEFAULT_LEVEL_DOUBLE 0.5
#define OMX_DEFAULT_PRESET_INPUTS 16
#define OMX_DEFAULT_PRESET_OUTPUTS 8
#define OMX_DEFAULT_THRESHOLDS_GROWTH_CONFIRM_FRAMES 2
#define OMX_DEFAULT_THRESHOLDS_GROWTH_MAX_DIP_DB 0.5f
#define OMX_DEFAULT_THRESHOLDS_GROWTH_MAX_DIP_DB_DOUBLE 0.5
#define OMX_DEFAULT_THRESHOLDS_GROWTH_MAX_SINGLE_FRAME_SHARE 0.5f
#define OMX_DEFAULT_THRESHOLDS_GROWTH_MAX_SINGLE_FRAME_SHARE_DOUBLE 0.5
#define OMX_DEFAULT_THRESHOLDS_GROWTH_MIN_DB_PER_FRAME 0.8f
#define OMX_DEFAULT_THRESHOLDS_GROWTH_MIN_DB_PER_FRAME_DOUBLE 0.8
#define OMX_DEFAULT_THRESHOLDS_GROWTH_MIN_TOTAL_RISE_DB 6
#define OMX_DEFAULT_THRESHOLDS_PAPR_DB 18
#define OMX_DEFAULT_THRESHOLDS_PERSIST_FRAMES 5
#define OMX_DEFAULT_THRESHOLDS_PHPR_DB 9
#define OMX_DEFAULT_THRESHOLDS_PNPR_DB 12
#define OMX_DEFAULT_THRESHOLDS_PSHR_MIN_DB 10
#define OMX_DEFAULT_THRESHOLDS_SUB_CLEAN_FRAMES 5
#define OMX_DEFAULT_WEB_PORT 8080
#define OMX_DESK_GAIN_RANGE_MAX_DB 55
#define OMX_DESK_GAIN_RANGE_MIN_DB -24
#define OMX_DESK_GAIN_RANGE_STEP_DB 1
#define OMX_DETECTOR_OVERSAMPLE_AUTO_MS 0.5f
#define OMX_DETECTOR_OVERSAMPLE_AUTO_MS_DOUBLE 0.5
#define OMX_DETECTOR_OVERSAMPLE_LATENCY_SAMPLES 72
#define OMX_DIVERGENCE_RANGE_MAX 1
#define OMX_DIVERGENCE_RANGE_MIN 0
#define OMX_DIVERGENCE_RANGE_STEP 0
#define OMX_DRIVE_BIAS_MAX 0.7071067811865476f
#define OMX_DRIVE_BIAS_MAX_DOUBLE 0.7071067811865476
#define OMX_EARLY_REFLECTION_FLOOR_DB -30
#define OMX_EARLY_REFLECTION_WINDOW_MS 80
#define OMX_EQ_DEFAULT_SAMPLE_RATE 48000
#define OMX_EQ_FREQ_RANGE_MAX 20000
#define OMX_EQ_FREQ_RANGE_MIN 20
#define OMX_EQ_FREQ_RANGE_STEP 10
#define OMX_EQ_GAIN_LIMIT_DB 15
#define OMX_EQ_GAIN_RANGE_MAX 15
#define OMX_EQ_GAIN_RANGE_MIN -15
#define OMX_EQ_GAIN_RANGE_STEP 0.5f
#define OMX_EQ_GAIN_RANGE_STEP_DOUBLE 0.5
#define OMX_EQ_MAX_BANDS 24
#define OMX_EQ_NOTCH_Q_RANGE_MAX 116
#define OMX_EQ_NOTCH_Q_RANGE_MIN 0.3f
#define OMX_EQ_NOTCH_Q_RANGE_MIN_DOUBLE 0.3
#define OMX_EQ_NOTCH_Q_RANGE_STEP 1
#define OMX_EQ_Q_RANGE_MAX 8
#define OMX_EQ_Q_RANGE_MIN 0.3f
#define OMX_EQ_Q_RANGE_MIN_DOUBLE 0.3
#define OMX_EQ_Q_RANGE_STEP 0.1f
#define OMX_EQ_Q_RANGE_STEP_DOUBLE 0.1
#define OMX_FAMILY_COMP_RATIO_BOUNDS_BASS_MAX 4
#define OMX_FAMILY_COMP_RATIO_BOUNDS_BASS_MIN 3
#define OMX_FAMILY_COMP_RATIO_BOUNDS_BRASS_MAX 4
#define OMX_FAMILY_COMP_RATIO_BOUNDS_BRASS_MIN 3
#define OMX_FAMILY_COMP_RATIO_BOUNDS_DRUMS_MAX 6
#define OMX_FAMILY_COMP_RATIO_BOUNDS_DRUMS_MIN 4
#define OMX_FAMILY_COMP_RATIO_BOUNDS_GUITAR_MAX 3
#define OMX_FAMILY_COMP_RATIO_BOUNDS_GUITAR_MIN 2
#define OMX_FAMILY_COMP_RATIO_BOUNDS_KEYS_MAX 3
#define OMX_FAMILY_COMP_RATIO_BOUNDS_KEYS_MIN 2
#define OMX_FAMILY_COMP_RATIO_BOUNDS_PERCUSSION_MAX 4
#define OMX_FAMILY_COMP_RATIO_BOUNDS_PERCUSSION_MIN 2
#define OMX_FAMILY_COMP_RATIO_BOUNDS_PLAYBACK_MAX 12
#define OMX_FAMILY_COMP_RATIO_BOUNDS_PLAYBACK_MIN 8
#define OMX_FAMILY_COMP_RATIO_BOUNDS_STRINGS_MAX 3
#define OMX_FAMILY_COMP_RATIO_BOUNDS_STRINGS_MIN 2
#define OMX_FAMILY_COMP_RATIO_BOUNDS_VOCALS_MAX 3
#define OMX_FAMILY_COMP_RATIO_BOUNDS_VOCALS_MIN 2
#define OMX_FAMILY_COMP_RATIO_BOUNDS_WIND_MAX 4
#define OMX_FAMILY_COMP_RATIO_BOUNDS_WIND_MIN 3
#define OMX_FBS_AUTO_BANDS_RANGE_MAX 24
#define OMX_FBS_AUTO_BANDS_RANGE_MIN 1
#define OMX_FBS_AUTO_BANDS_RANGE_STEP 1
#define OMX_FBS_COOLDOWN_MINUTES_RANGE_MAX 120
#define OMX_FBS_COOLDOWN_MINUTES_RANGE_MIN 0
#define OMX_FBS_COOLDOWN_MINUTES_RANGE_STEP 1
#define OMX_FBS_DEFAULT_COOLDOWN_MINUTES 10
#define OMX_FBS_DEFAULT_HOLD_SECONDS 5
#define OMX_FBS_DEFAULT_MAX_AUTO_BANDS 6
#define OMX_FBS_DEFAULT_MERGE_CENTS 100
#define OMX_FBS_DEFAULT_NOTCH_Q 116
#define OMX_FBS_DEFAULT_SENSITIVITY 0
#define OMX_FBS_FLOOR_LIN 1e-12f
#define OMX_FBS_FLOOR_LIN_DOUBLE 1e-12
#define OMX_FBS_HOLD_SECONDS_RANGE_MAX 300
#define OMX_FBS_HOLD_SECONDS_RANGE_MIN 1
#define OMX_FBS_HOLD_SECONDS_RANGE_STEP 1
#define OMX_FBS_LIFT_RAMP_MS 3000
#define OMX_FBS_MAX_CUT_DB -24
#define OMX_FBS_MAX_NOTCH_DEPTH_DB 18
#define OMX_FBS_MERGE_CENTS_RANGE_MAX 600
#define OMX_FBS_MERGE_CENTS_RANGE_MIN 0
#define OMX_FBS_MERGE_CENTS_RANGE_STEP 10
#define OMX_FBS_PAPR_GUARD_BINS 2
#define OMX_FBS_PHPR_HARMONICS 3
#define OMX_FBS_PNPR_GUARD_BINS 1
#define OMX_FBS_PNPR_RADIUS_BINS 3
#define OMX_FBS_PSHR_SELF_SKIP_BINS 3
#define OMX_FBS_RECLAMP_BACKOFF_CAP 3
#define OMX_FBS_RECLAMP_DEEPEN_DB 3
#define OMX_FBS_RELEASE_DONE_DB 1
#define OMX_FBS_RELEASE_DWELL_MS 8000
#define OMX_FBS_RELEASE_RATIO 0.6666666666666666f
#define OMX_FBS_RELEASE_RATIO_DOUBLE 0.6666666666666666
#define OMX_FBS_RING_HZ_MAX 16000
#define OMX_FBS_RING_HZ_MIN 60
#define OMX_FBS_SENSITIVITY_RANGE_MAX 1
#define OMX_FBS_SENSITIVITY_RANGE_MIN 0
#define OMX_FBS_SENSITIVITY_RANGE_STEP 0.05f
#define OMX_FBS_SENSITIVITY_RANGE_STEP_DOUBLE 0.05
#define OMX_FBS_TRACK_SLOTS 512
#define OMX_FDELAY_MOD_READ_ORDER 3
#define OMX_FDELAY_READ_L1_NORM 1.25f
#define OMX_FDELAY_READ_L1_NORM_DOUBLE 1.25
#define OMX_GATE_KEY_VOICE_BAND_HP_HZ 120
#define OMX_GATE_KEY_VOICE_BAND_LP_HZ 8000
#define OMX_GATE_RANGE_FLOOR_DB -90
#define OMX_GEQ_BANDS 31
#define OMX_GEQ_BAND_Q 4.3f
#define OMX_GEQ_BAND_Q_DOUBLE 4.3
#define OMX_GROWTH_CONFIRM_FRAMES 2
#define OMX_GROWTH_MAX_DIP_DB 0.5f
#define OMX_GROWTH_MAX_DIP_DB_DOUBLE 0.5
#define OMX_GROWTH_MAX_SINGLE_FRAME_SHARE 0.5f
#define OMX_GROWTH_MAX_SINGLE_FRAME_SHARE_DOUBLE 0.5
#define OMX_GROWTH_MIN_DB_PER_FRAME 0.8f
#define OMX_GROWTH_MIN_DB_PER_FRAME_DOUBLE 0.8
#define OMX_GROWTH_MIN_TOTAL_RISE_DB 6
#define OMX_GROWTH_WINDOW_FRAMES 5
#define OMX_HEAD_AMP_GAIN_MAX_DB 55
#define OMX_HEAD_AMP_GAIN_MIN_DB 0
#define OMX_HOSTED_STAGE_CLAMP_DBFS 24
#define OMX_HOSTED_STAGE_EVENTS_PER_BLOCK 64
#define OMX_HOSTED_STAGE_NON_FINITE_STRIKES 3
#define OMX_HOSTED_STAGE_PARAM_QUEUE_DEPTH 256
#define OMX_HOSTED_STAGE_UNPUBLISH_POLL_US 100
#define OMX_HOSTED_STAGE_UNPUBLISH_TIMEOUT_US 2000000
#define OMX_HOSTED_STAGE_WARMUP_BLOCKS 64
#define OMX_HOSTED_STAGE_WARMUP_LEVEL_DBFS -6
#define OMX_HOSTED_STAGE_WORKER_POLL_US 1000
#define OMX_HOSTED_STAGE_WORKER_RING_BYTES 16384
#define OMX_HPF_FREQ_RANGE_MAX 1000
#define OMX_HPF_FREQ_RANGE_MIN 20
#define OMX_HPF_FREQ_RANGE_STEP 10
#define OMX_HRP_AMOUNT_RANGE_MAX 1
#define OMX_HRP_AMOUNT_RANGE_MIN 0
#define OMX_HRP_AMOUNT_RANGE_STEP 0
#define OMX_HRP_ATTRIBUTION_CENTS 60
#define OMX_HRP_AUTO_BANDS_RANGE_MAX 24
#define OMX_HRP_AUTO_BANDS_RANGE_MIN 1
#define OMX_HRP_AUTO_BANDS_RANGE_STEP 1
#define OMX_HRP_BAND_Q 5
#define OMX_HRP_COLLISION_CENTS 100
#define OMX_HRP_DEFAULT_MAX_AUTO_BANDS 8
#define OMX_HRP_EXCESS_THRESHOLD_DB 3
#define OMX_HRP_FAMILY_SEARCH_BASS_F0_MAX_HZ 400
#define OMX_HRP_FAMILY_SEARCH_BASS_F0_MIN_HZ 25
#define OMX_HRP_FAMILY_SEARCH_BASS_MAX_VOICES 2
#define OMX_HRP_FAMILY_SEARCH_BRASS_F0_MAX_HZ 1400
#define OMX_HRP_FAMILY_SEARCH_BRASS_F0_MIN_HZ 40
#define OMX_HRP_FAMILY_SEARCH_BRASS_MAX_VOICES 2
#define OMX_HRP_FAMILY_SEARCH_DRUMS_F0_MAX_HZ 400
#define OMX_HRP_FAMILY_SEARCH_DRUMS_F0_MIN_HZ 35
#define OMX_HRP_FAMILY_SEARCH_DRUMS_MAX_VOICES 1
#define OMX_HRP_FAMILY_SEARCH_GUITAR_F0_MAX_HZ 1400
#define OMX_HRP_FAMILY_SEARCH_GUITAR_F0_MIN_HZ 60
#define OMX_HRP_FAMILY_SEARCH_GUITAR_MAX_VOICES 6
#define OMX_HRP_FAMILY_SEARCH_KEYS_F0_MAX_HZ 4200
#define OMX_HRP_FAMILY_SEARCH_KEYS_F0_MIN_HZ 27.5f
#define OMX_HRP_FAMILY_SEARCH_KEYS_F0_MIN_HZ_DOUBLE 27.5
#define OMX_HRP_FAMILY_SEARCH_KEYS_MAX_VOICES 8
#define OMX_HRP_FAMILY_SEARCH_PERCUSSION_F0_MAX_HZ 1200
#define OMX_HRP_FAMILY_SEARCH_PERCUSSION_F0_MIN_HZ 60
#define OMX_HRP_FAMILY_SEARCH_PERCUSSION_MAX_VOICES 1
#define OMX_HRP_FAMILY_SEARCH_PLAYBACK_F0_MAX_HZ 2100
#define OMX_HRP_FAMILY_SEARCH_PLAYBACK_F0_MIN_HZ 25
#define OMX_HRP_FAMILY_SEARCH_PLAYBACK_MAX_VOICES 8
#define OMX_HRP_FAMILY_SEARCH_STRINGS_F0_MAX_HZ 2800
#define OMX_HRP_FAMILY_SEARCH_STRINGS_F0_MIN_HZ 40
#define OMX_HRP_FAMILY_SEARCH_STRINGS_MAX_VOICES 8
#define OMX_HRP_FAMILY_SEARCH_VOCALS_F0_MAX_HZ 1200
#define OMX_HRP_FAMILY_SEARCH_VOCALS_F0_MIN_HZ 80
#define OMX_HRP_FAMILY_SEARCH_VOCALS_MAX_VOICES 2
#define OMX_HRP_FAMILY_SEARCH_WIND_F0_MAX_HZ 2600
#define OMX_HRP_FAMILY_SEARCH_WIND_F0_MIN_HZ 55
#define OMX_HRP_FAMILY_SEARCH_WIND_MAX_VOICES 2
#define OMX_HRP_GAIN_STEP_DB 2
#define OMX_HRP_HARMONIC_COUNT 12
#define OMX_HRP_MAX_BOOST_DB 0
#define OMX_HRP_MAX_CUT_DB 6
#define OMX_HRP_MAX_VOICES 8
#define OMX_HRP_TIER_CROSSOVER_HZ 1000
#define OMX_INPUT_ALIGN_DELAY_RANGE_MAX 100
#define OMX_INPUT_ALIGN_DELAY_RANGE_MIN 0
#define OMX_INPUT_ALIGN_DELAY_RANGE_STEP 0.01f
#define OMX_INPUT_ALIGN_DELAY_RANGE_STEP_DOUBLE 0.01
#define OMX_JOIN_LANE_NS_176400 0.261f
#define OMX_JOIN_LANE_NS_176400_DOUBLE 0.261
#define OMX_JOIN_LANE_NS_192000 0.261f
#define OMX_JOIN_LANE_NS_192000_DOUBLE 0.261
#define OMX_JOIN_LANE_NS_44100 0.25f
#define OMX_JOIN_LANE_NS_44100_DOUBLE 0.25
#define OMX_JOIN_LANE_NS_48000 0.25f
#define OMX_JOIN_LANE_NS_48000_DOUBLE 0.25
#define OMX_JOIN_LANE_NS_88200 0.25f
#define OMX_JOIN_LANE_NS_88200_DOUBLE 0.25
#define OMX_JOIN_LANE_NS_96000 0.25f
#define OMX_JOIN_LANE_NS_96000_DOUBLE 0.25
#define OMX_LANE_WALK_NS_176400 172.9f
#define OMX_LANE_WALK_NS_176400_DOUBLE 172.9
#define OMX_LANE_WALK_NS_192000 172.9f
#define OMX_LANE_WALK_NS_192000_DOUBLE 172.9
#define OMX_LANE_WALK_NS_44100 173.1f
#define OMX_LANE_WALK_NS_44100_DOUBLE 173.1
#define OMX_LANE_WALK_NS_48000 173.1f
#define OMX_LANE_WALK_NS_48000_DOUBLE 173.1
#define OMX_LANE_WALK_NS_88200 173.1f
#define OMX_LANE_WALK_NS_88200_DOUBLE 173.1
#define OMX_LANE_WALK_NS_96000 173.1f
#define OMX_LANE_WALK_NS_96000_DOUBLE 173.1
#define OMX_LPF_FREQ_RANGE_MAX 20000
#define OMX_LPF_FREQ_RANGE_MIN 1000
#define OMX_LPF_FREQ_RANGE_STEP 10
#define OMX_MACHINE_BANDS_RANGE_MAX 24
#define OMX_MACHINE_BANDS_RANGE_MIN 0
#define OMX_MACHINE_BANDS_RANGE_STEP 1
#define OMX_MAX_FREQ_HZ 20000
#define OMX_MAX_INPUT_CHANNELS 128
#define OMX_MAX_SYNC_DIVISION 16
#define OMX_METER_FLAG_LIMIT_MAX 1
#define OMX_METER_FLAG_LIMIT_MIN 0
#define OMX_METER_FLAG_LIMIT_STEP 0.00392156862745098f
#define OMX_METER_FLAG_LIMIT_STEP_DOUBLE 0.00392156862745098
#define OMX_METER_FLOOR_DB -60
#define OMX_METER_LEVEL_LIMIT_MAX 0
#define OMX_METER_LEVEL_LIMIT_MIN -96
#define OMX_METER_LEVEL_LIMIT_STEP 0.3764705882352941f
#define OMX_METER_LEVEL_LIMIT_STEP_DOUBLE 0.3764705882352941
#define OMX_METER_REDUCTION_LIMIT_MAX 0
#define OMX_METER_REDUCTION_LIMIT_MIN -60
#define OMX_METER_REDUCTION_LIMIT_STEP 0.23529411764705882f
#define OMX_METER_REDUCTION_LIMIT_STEP_DOUBLE 0.23529411764705882
#define OMX_METER_RELEASE_PER_FRAME 0.012f
#define OMX_METER_RELEASE_PER_FRAME_DOUBLE 0.012
#define OMX_METER_STEP_HYSTERESIS 0.25f
#define OMX_METER_STEP_HYSTERESIS_DOUBLE 0.25
#define OMX_MIN_FRAMES 4
#define OMX_MIN_FREQ_HZ 20
#define OMX_MIN_INPUT_CHANNELS 8
#define OMX_MIN_SYNC_DIVISION 0.0625f
#define OMX_MIN_SYNC_DIVISION_DOUBLE 0.0625
#define OMX_MONO_FOLD_COEF 0.5f
#define OMX_MONO_FOLD_COEF_DOUBLE 0.5
#define OMX_NATIVE_INSERT_STAGE 9
#define OMX_NATIVE_STAGE_ID_CHORUS 6
#define OMX_NATIVE_STAGE_ID_DELAY 4
#define OMX_NATIVE_STAGE_ID_DE_ESSER 8
#define OMX_NATIVE_STAGE_ID_DRIVE 3
#define OMX_NATIVE_STAGE_ID_DYNAMICS 2
#define OMX_NATIVE_STAGE_ID_EQ 1
#define OMX_NATIVE_STAGE_ID_FLANGER 7
#define OMX_NATIVE_STAGE_ID_GATE 0
#define OMX_NATIVE_STAGE_ID_REVERB 5
#define OMX_NORMALIZED_RANGE_MAX 1
#define OMX_NORMALIZED_RANGE_MIN 0
#define OMX_NORMALIZED_RANGE_STEP 0
#define OMX_NO_BUSES_AUX 0
#define OMX_NO_BUSES_DCA 0
#define OMX_NO_BUSES_FX_RETURN 0
#define OMX_NO_BUSES_GROUP 0
#define OMX_NO_BUSES_MAIN 0
#define OMX_NO_BUSES_MATRIX 0
#define OMX_NO_BUSES_MIX_MINUS 0
#define OMX_OPERATOR_EQ_BANDS_RESERVE 9
#define OMX_OSCILLATOR_FREQ_RANGE_MAX 20000
#define OMX_OSCILLATOR_FREQ_RANGE_MIN 20
#define OMX_OSCILLATOR_FREQ_RANGE_STEP 10
#define OMX_OUTPUT_DELAY_RANGE_MAX 1000
#define OMX_OUTPUT_DELAY_RANGE_MIN 0
#define OMX_OUTPUT_DELAY_RANGE_STEP 1
#define OMX_OUTPUT_TRIM_RANGE_MAX 12
#define OMX_OUTPUT_TRIM_RANGE_MIN -40
#define OMX_OUTPUT_TRIM_RANGE_STEP 1
#define OMX_PAN_RANGE_MAX 1
#define OMX_PAN_RANGE_MIN -1
#define OMX_PAN_RANGE_STEP 0
#define OMX_PATCH_SCHEMA_VERSION 1
#define OMX_PERF_REFRESH_LIMIT_MAX 60000
#define OMX_PERF_REFRESH_LIMIT_MIN 250
#define OMX_PERF_REFRESH_LIMIT_STEP 0
#define OMX_PITCH_PREFILTER_CEILING_HZ 20000
#define OMX_PITCH_PREFILTER_Q 0.7071067811865476f
#define OMX_PITCH_PREFILTER_Q_DOUBLE 0.7071067811865476
#define OMX_PITCH_WINDOW_MS 40
#define OMX_PROGRAM_RELEASE_CHARGE_MS 1000
#define OMX_PROGRAM_RELEASE_DISCHARGE_MS 5000
#define OMX_PROGRAM_RELEASE_PROFILES_OPTO_FAST_MS 70
#define OMX_PROGRAM_RELEASE_PROFILES_OPTO_SHARE 0.5f
#define OMX_PROGRAM_RELEASE_PROFILES_OPTO_SHARE_DOUBLE 0.5
#define OMX_PROGRAM_RELEASE_PROFILES_OPTO_SLOW_MAX_MS 1100
#define OMX_PROGRAM_RELEASE_PROFILES_OPTO_SLOW_MIN_MS 110
#define OMX_PSHR_MIN_DB 10
#define OMX_REAC_AUDIO_FABRIC_CEILING 39
#define OMX_REAC_AUDIO_FABRIC_SLOTS 40
#define OMX_REAC_CFG_RATE_44100 44100
#define OMX_REAC_CFG_RATE_48000 48000
#define OMX_REAC_CFG_RATE_96000 96000
#define OMX_REAC_CFG_RATE_COUNT 3
#define OMX_REAC_CFG_ROLE_MASTER 0
#define OMX_REAC_CFG_ROLE_SLAVE 1
#define OMX_REAC_HEADAMP_CEILING 47
#define OMX_REAC_HEADAMP_RING 49
#define OMX_REAC_HEADAMP_SLOTS 48
#define OMX_REAC_HEAD_AMP_GAIN_RANGE_MAX_DB 55
#define OMX_REAC_HEAD_AMP_GAIN_RANGE_MIN_DB 0
#define OMX_REAC_HEAD_AMP_GAIN_RANGE_STEP_DB 1
#define OMX_REVERB_CUT_RANGE_MAX 20000
#define OMX_REVERB_CUT_RANGE_MIN 0
#define OMX_REVERB_CUT_RANGE_STEP 10
#define OMX_RME_PHONES_BALANCE_RANGE_MAX 6
#define OMX_RME_PHONES_BALANCE_RANGE_MIN -6
#define OMX_RME_PHONES_BALANCE_RANGE_STEP 0
#define OMX_RME_TRIM_RANGE_MAX 6
#define OMX_RME_TRIM_RANGE_MIN -60
#define OMX_RME_TRIM_RANGE_STEP 0
#define OMX_ROOM_MODE_BAND_HIGH_HZ 300
#define OMX_ROOM_MODE_BAND_LOW_HZ 20
#define OMX_ROOM_MODE_MAX_CUT_DB 15
#define OMX_ROOM_MODE_MIN_ABOVE_MEDIAN_DB 6
#define OMX_ROOM_MODE_MIN_POSITIONS 2
#define OMX_ROTARY_BASE_MS 0.1f
#define OMX_ROTARY_BASE_MS_DOUBLE 0.1
#define OMX_ROTARY_CROSSOVER_HZ 800
#define OMX_ROTARY_DRUM_ACCEL_MS 1700
#define OMX_ROTARY_DRUM_AM 0.3f
#define OMX_ROTARY_DRUM_AM_DOUBLE 0.3
#define OMX_ROTARY_DRUM_DECEL_MS 1800
#define OMX_ROTARY_DRUM_DOPPLER_MS 0.29f
#define OMX_ROTARY_DRUM_DOPPLER_MS_DOUBLE 0.29
#define OMX_ROTARY_HORN_ACCEL_MS 330
#define OMX_ROTARY_HORN_AM 0.5f
#define OMX_ROTARY_HORN_AM_DOUBLE 0.5
#define OMX_ROTARY_HORN_DECEL_MS 500
#define OMX_ROTARY_HORN_DOPPLER_MS 0.44f
#define OMX_ROTARY_HORN_DOPPLER_MS_DOUBLE 0.44
#define OMX_ROTARY_RING_FLOATS 256
#define OMX_ROTARY_STOP_EPS 0.0001f
#define OMX_ROTARY_STOP_EPS_DOUBLE 0.0001
#define OMX_RTA_FFT_SIZE_MAX 32768
#define OMX_RTA_TAP_GATE_DB -60
#define OMX_RTA_TARGET_BIN_HZ 5.9f
#define OMX_RTA_TARGET_BIN_HZ_DOUBLE 5.9
#define OMX_RT_ADMISSION_CEILING_RATIO 0.6f
#define OMX_RT_ADMISSION_CEILING_RATIO_DOUBLE 0.6
#define OMX_RT_CAPACITY_TOLERANCE 0.1f
#define OMX_RT_CAPACITY_TOLERANCE_DOUBLE 0.1
#define OMX_RT_HARD_TARGET_QUANTUM 128
#define OMX_RT_HARD_TARGET_RATE 192000
#define OMX_RT_HEADROOM_REFUSE_RATIO 0.8f
#define OMX_RT_HEADROOM_REFUSE_RATIO_DOUBLE 0.8
#define OMX_RT_HEADROOM_WARN_RATIO 0.6f
#define OMX_RT_HEADROOM_WARN_RATIO_DOUBLE 0.6
#define OMX_RT_PREDICTION_TOLERANCE 0.1f
#define OMX_RT_PREDICTION_TOLERANCE_DOUBLE 0.1
#define OMX_RT_SPLIT_ECORE_WEIGHT_SEED 0.5f
#define OMX_RT_SPLIT_ECORE_WEIGHT_SEED_DOUBLE 0.5
#define OMX_RT_STAGE_MAX_FACTOR 2
#define OMX_SCENE_SCHEMA_VERSION 1
#define OMX_SEND_NS_PER_SAMPLE_176400 0.193f
#define OMX_SEND_NS_PER_SAMPLE_176400_DOUBLE 0.193
#define OMX_SEND_NS_PER_SAMPLE_192000 0.193f
#define OMX_SEND_NS_PER_SAMPLE_192000_DOUBLE 0.193
#define OMX_SEND_NS_PER_SAMPLE_44100 0.193f
#define OMX_SEND_NS_PER_SAMPLE_44100_DOUBLE 0.193
#define OMX_SEND_NS_PER_SAMPLE_48000 0.193f
#define OMX_SEND_NS_PER_SAMPLE_48000_DOUBLE 0.193
#define OMX_SEND_NS_PER_SAMPLE_88200 0.193f
#define OMX_SEND_NS_PER_SAMPLE_88200_DOUBLE 0.193
#define OMX_SEND_NS_PER_SAMPLE_96000 0.193f
#define OMX_SEND_NS_PER_SAMPLE_96000_DOUBLE 0.193
#define OMX_SENS_VALUE_MAX 55
#define OMX_SENS_VALUE_MIN 0
#define OMX_SESSION_SCHEMA_VERSION 1
#define OMX_SPEAKER_ALIGN_BAND_HIGH_HZ 4000
#define OMX_SPEAKER_ALIGN_BAND_LOW_HZ 125
#define OMX_SPECTRUM_LEVEL_LIMIT_MAX 0
#define OMX_SPECTRUM_LEVEL_LIMIT_MIN -100
#define OMX_SPECTRUM_LEVEL_LIMIT_STEP 0.39215686274509803f
#define OMX_SPECTRUM_LEVEL_LIMIT_STEP_DOUBLE 0.39215686274509803
#define OMX_SPEED_OF_SOUND_M_S 343
#define OMX_STAGE_COST_NS_PER_SAMPLE_CHORUS_176400 57.1f
#define OMX_STAGE_COST_NS_PER_SAMPLE_CHORUS_176400_DOUBLE 57.1
#define OMX_STAGE_COST_NS_PER_SAMPLE_CHORUS_192000 57.1f
#define OMX_STAGE_COST_NS_PER_SAMPLE_CHORUS_192000_DOUBLE 57.1
#define OMX_STAGE_COST_NS_PER_SAMPLE_CHORUS_44100 57.179f
#define OMX_STAGE_COST_NS_PER_SAMPLE_CHORUS_44100_DOUBLE 57.179
#define OMX_STAGE_COST_NS_PER_SAMPLE_CHORUS_48000 57.179f
#define OMX_STAGE_COST_NS_PER_SAMPLE_CHORUS_48000_DOUBLE 57.179
#define OMX_STAGE_COST_NS_PER_SAMPLE_CHORUS_88200 57.179f
#define OMX_STAGE_COST_NS_PER_SAMPLE_CHORUS_88200_DOUBLE 57.179
#define OMX_STAGE_COST_NS_PER_SAMPLE_CHORUS_96000 57.179f
#define OMX_STAGE_COST_NS_PER_SAMPLE_CHORUS_96000_DOUBLE 57.179
#define OMX_STAGE_COST_NS_PER_SAMPLE_DELAY_176400 2.424f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DELAY_176400_DOUBLE 2.424
#define OMX_STAGE_COST_NS_PER_SAMPLE_DELAY_192000 2.424f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DELAY_192000_DOUBLE 2.424
#define OMX_STAGE_COST_NS_PER_SAMPLE_DELAY_44100 2.422f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DELAY_44100_DOUBLE 2.422
#define OMX_STAGE_COST_NS_PER_SAMPLE_DELAY_48000 2.422f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DELAY_48000_DOUBLE 2.422
#define OMX_STAGE_COST_NS_PER_SAMPLE_DELAY_88200 2.422f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DELAY_88200_DOUBLE 2.422
#define OMX_STAGE_COST_NS_PER_SAMPLE_DELAY_96000 2.422f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DELAY_96000_DOUBLE 2.422
#define OMX_STAGE_COST_NS_PER_SAMPLE_DE_ESSER_176400 16.954f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DE_ESSER_176400_DOUBLE 16.954
#define OMX_STAGE_COST_NS_PER_SAMPLE_DE_ESSER_192000 16.954f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DE_ESSER_192000_DOUBLE 16.954
#define OMX_STAGE_COST_NS_PER_SAMPLE_DE_ESSER_44100 16.861f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DE_ESSER_44100_DOUBLE 16.861
#define OMX_STAGE_COST_NS_PER_SAMPLE_DE_ESSER_48000 16.861f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DE_ESSER_48000_DOUBLE 16.861
#define OMX_STAGE_COST_NS_PER_SAMPLE_DE_ESSER_88200 16.861f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DE_ESSER_88200_DOUBLE 16.861
#define OMX_STAGE_COST_NS_PER_SAMPLE_DE_ESSER_96000 16.861f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DE_ESSER_96000_DOUBLE 16.861
#define OMX_STAGE_COST_NS_PER_SAMPLE_DRIVE_176400 58.135f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DRIVE_176400_DOUBLE 58.135
#define OMX_STAGE_COST_NS_PER_SAMPLE_DRIVE_192000 58.135f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DRIVE_192000_DOUBLE 58.135
#define OMX_STAGE_COST_NS_PER_SAMPLE_DRIVE_44100 58.348f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DRIVE_44100_DOUBLE 58.348
#define OMX_STAGE_COST_NS_PER_SAMPLE_DRIVE_48000 58.348f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DRIVE_48000_DOUBLE 58.348
#define OMX_STAGE_COST_NS_PER_SAMPLE_DRIVE_88200 58.348f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DRIVE_88200_DOUBLE 58.348
#define OMX_STAGE_COST_NS_PER_SAMPLE_DRIVE_96000 58.348f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DRIVE_96000_DOUBLE 58.348
#define OMX_STAGE_COST_NS_PER_SAMPLE_DYNAMICS_176400 89.678f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DYNAMICS_176400_DOUBLE 89.678
#define OMX_STAGE_COST_NS_PER_SAMPLE_DYNAMICS_192000 89.678f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DYNAMICS_192000_DOUBLE 89.678
#define OMX_STAGE_COST_NS_PER_SAMPLE_DYNAMICS_44100 89.839f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DYNAMICS_44100_DOUBLE 89.839
#define OMX_STAGE_COST_NS_PER_SAMPLE_DYNAMICS_48000 89.839f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DYNAMICS_48000_DOUBLE 89.839
#define OMX_STAGE_COST_NS_PER_SAMPLE_DYNAMICS_88200 89.839f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DYNAMICS_88200_DOUBLE 89.839
#define OMX_STAGE_COST_NS_PER_SAMPLE_DYNAMICS_96000 89.839f
#define OMX_STAGE_COST_NS_PER_SAMPLE_DYNAMICS_96000_DOUBLE 89.839
#define OMX_STAGE_COST_NS_PER_SAMPLE_EQ_176400 20.867f
#define OMX_STAGE_COST_NS_PER_SAMPLE_EQ_176400_DOUBLE 20.867
#define OMX_STAGE_COST_NS_PER_SAMPLE_EQ_192000 20.867f
#define OMX_STAGE_COST_NS_PER_SAMPLE_EQ_192000_DOUBLE 20.867
#define OMX_STAGE_COST_NS_PER_SAMPLE_EQ_44100 20.839f
#define OMX_STAGE_COST_NS_PER_SAMPLE_EQ_44100_DOUBLE 20.839
#define OMX_STAGE_COST_NS_PER_SAMPLE_EQ_48000 20.839f
#define OMX_STAGE_COST_NS_PER_SAMPLE_EQ_48000_DOUBLE 20.839
#define OMX_STAGE_COST_NS_PER_SAMPLE_EQ_88200 20.839f
#define OMX_STAGE_COST_NS_PER_SAMPLE_EQ_88200_DOUBLE 20.839
#define OMX_STAGE_COST_NS_PER_SAMPLE_EQ_96000 20.839f
#define OMX_STAGE_COST_NS_PER_SAMPLE_EQ_96000_DOUBLE 20.839
#define OMX_STAGE_COST_NS_PER_SAMPLE_FLANGER_176400 32.049f
#define OMX_STAGE_COST_NS_PER_SAMPLE_FLANGER_176400_DOUBLE 32.049
#define OMX_STAGE_COST_NS_PER_SAMPLE_FLANGER_192000 32.049f
#define OMX_STAGE_COST_NS_PER_SAMPLE_FLANGER_192000_DOUBLE 32.049
#define OMX_STAGE_COST_NS_PER_SAMPLE_FLANGER_44100 32.093f
#define OMX_STAGE_COST_NS_PER_SAMPLE_FLANGER_44100_DOUBLE 32.093
#define OMX_STAGE_COST_NS_PER_SAMPLE_FLANGER_48000 32.093f
#define OMX_STAGE_COST_NS_PER_SAMPLE_FLANGER_48000_DOUBLE 32.093
#define OMX_STAGE_COST_NS_PER_SAMPLE_FLANGER_88200 32.093f
#define OMX_STAGE_COST_NS_PER_SAMPLE_FLANGER_88200_DOUBLE 32.093
#define OMX_STAGE_COST_NS_PER_SAMPLE_FLANGER_96000 32.093f
#define OMX_STAGE_COST_NS_PER_SAMPLE_FLANGER_96000_DOUBLE 32.093
#define OMX_STAGE_COST_NS_PER_SAMPLE_GATE_176400 9.507f
#define OMX_STAGE_COST_NS_PER_SAMPLE_GATE_176400_DOUBLE 9.507
#define OMX_STAGE_COST_NS_PER_SAMPLE_GATE_192000 9.507f
#define OMX_STAGE_COST_NS_PER_SAMPLE_GATE_192000_DOUBLE 9.507
#define OMX_STAGE_COST_NS_PER_SAMPLE_GATE_44100 9.497f
#define OMX_STAGE_COST_NS_PER_SAMPLE_GATE_44100_DOUBLE 9.497
#define OMX_STAGE_COST_NS_PER_SAMPLE_GATE_48000 9.497f
#define OMX_STAGE_COST_NS_PER_SAMPLE_GATE_48000_DOUBLE 9.497
#define OMX_STAGE_COST_NS_PER_SAMPLE_GATE_88200 9.497f
#define OMX_STAGE_COST_NS_PER_SAMPLE_GATE_88200_DOUBLE 9.497
#define OMX_STAGE_COST_NS_PER_SAMPLE_GATE_96000 9.497f
#define OMX_STAGE_COST_NS_PER_SAMPLE_GATE_96000_DOUBLE 9.497
#define OMX_STAGE_COST_NS_PER_SAMPLE_REVERB_176400 20.897f
#define OMX_STAGE_COST_NS_PER_SAMPLE_REVERB_176400_DOUBLE 20.897
#define OMX_STAGE_COST_NS_PER_SAMPLE_REVERB_192000 20.897f
#define OMX_STAGE_COST_NS_PER_SAMPLE_REVERB_192000_DOUBLE 20.897
#define OMX_STAGE_COST_NS_PER_SAMPLE_REVERB_44100 20.117f
#define OMX_STAGE_COST_NS_PER_SAMPLE_REVERB_44100_DOUBLE 20.117
#define OMX_STAGE_COST_NS_PER_SAMPLE_REVERB_48000 20.117f
#define OMX_STAGE_COST_NS_PER_SAMPLE_REVERB_48000_DOUBLE 20.117
#define OMX_STAGE_COST_NS_PER_SAMPLE_REVERB_88200 20.117f
#define OMX_STAGE_COST_NS_PER_SAMPLE_REVERB_88200_DOUBLE 20.117
#define OMX_STAGE_COST_NS_PER_SAMPLE_REVERB_96000 20.117f
#define OMX_STAGE_COST_NS_PER_SAMPLE_REVERB_96000_DOUBLE 20.117
#define OMX_STRIP_QUANTUM 4
#define OMX_SUBHARMONIC_RADIUS_BINS 2
#define OMX_SURFACE_BANK_WIDTH 8
#define OMX_SYNC_NS_176400 4122
#define OMX_SYNC_NS_192000 4122
#define OMX_SYNC_NS_44100 4112
#define OMX_SYNC_NS_48000 4112
#define OMX_SYNC_NS_88200 4112
#define OMX_SYNC_NS_96000 4112
#define OMX_T20_LOWER_DB -25
#define OMX_T20_UPPER_DB -5
#define OMX_TAKE_RENDER_SCHEMA_VERSION 1
#define OMX_TAKE_REVERSE_RENDER_SCHEMA_VERSION 1
#define OMX_TAKE_SCHEMA_VERSION 1
#define OMX_TAPER_FLOOR_DB -90
#define OMX_TAP_AT_CHAIN_INPUT -1
#define OMX_TAP_RESET_MS 2000
#define OMX_TAP_WINDOW 4
#define OMX_TIER_CROSSOVER_HZ 300
#define OMX_TRANSIENT_FAST_ATTACK_MS 0.5f
#define OMX_TRANSIENT_FAST_ATTACK_MS_DOUBLE 0.5
#define OMX_TRANSIENT_FAST_RELEASE_MS 20
#define OMX_TRANSIENT_FLOOR_LIN 0.00001f
#define OMX_TRANSIENT_FLOOR_LIN_DOUBLE 0.00001
#define OMX_TRANSIENT_REF_DB 6
#define OMX_TRIM_RANGE_MAX_DB 24
#define OMX_TRIM_RANGE_MIN_DB -24
#define OMX_TRIM_RANGE_STEP_DB 0.1f
#define OMX_TRIM_RANGE_STEP_DB_DOUBLE 0.1
#define OMX_UNITY_POSITION 0.75f
#define OMX_UNITY_POSITION_DOUBLE 0.75
#define OMX_XOVER_LR2_SECTION_Q 0.5f
#define OMX_XOVER_LR2_SECTION_Q_DOUBLE 0.5
#define OMX_XOVER_LR4_SECTION_Q 0.7071067811865476f
#define OMX_XOVER_LR4_SECTION_Q_DOUBLE 0.7071067811865476
#define OMX_XOVER_PARTITION_TOLERANCE 0.00001f
#define OMX_XOVER_PARTITION_TOLERANCE_DOUBLE 0.00001

/* The CLAP host object's extension ids (packages/plugin-qualify/src/hosting-suitability.ts,
 * OMX_CLAP_HOST_EXTENSIONS; 2026-09-26-clap-hosting-path.md §5) — read by mix_clap_host.c. */
#define OMX_CLAP_HOST_EXTENSION_COUNT 6u
#define OMX_CLAP_HOST_EXTENSIONS_INIT { "clap.log", "clap.thread-check", "clap.latency", "clap.params", "clap.audio-ports", "clap.state", NULL }

/* EVERY declared record set (packages/core/src/declared-sets.ts over the core barrel and
 * @freemixer/declarations; dsp-primitives §7) — one block, sorted by set, named by nobody: HOST_VERBS
 * (2026-09-29-host-backend-one-contract.md §4, read by mix_host_backend.test.c against the fork's
 * scenario list), … OMX_<SET>_INIT is one { … } row per declared row, fields in declaration order: a
 * string as a C string literal, a boolean as 0/1, a number as the scalar literal. */
#define OMX_HOST_VERBS_COUNT 9u
#define OMX_HOST_VERBS_INIT { { "add", 1 }, { "remove", 1 }, { "bypass", 1 }, { "param_set", 1 }, { "param_get", 1 }, { "patch_set", 0 }, { "preset_load", 1 }, { "connect", 1 }, { "disconnect", 1 } }

/* The running check (dsp-primitives §7): every declared scalar by name with the macro ITSELF, so an
 * entry carries what the including binary COMPILED. ONE translation unit defines
 * OMX_DECLARED_SCALARS_TABLE before including this header (declared_scalars.c) and exports it. */
#ifdef OMX_DECLARED_SCALARS_TABLE
struct omx_declared_scalar { const char *name; double value; };
static const struct omx_declared_scalar OMX_DECLARED_SCALARS[] = {
  { "ALIGN_TRUST_COHERENCE", (double)OMX_ALIGN_TRUST_COHERENCE },
  { "ALLPASS_UNITY_TOLERANCE", (double)OMX_ALLPASS_UNITY_TOLERANCE },
  { "BAND_F_MAX_CAP", (double)OMX_BAND_F_MAX_CAP },
  { "BAND_F_MIN", (double)OMX_BAND_F_MIN },
  { "BAND_GATE_DB", (double)OMX_BAND_GATE_DB },
  { "BPM_MAX", (double)OMX_BPM_MAX },
  { "BPM_MIN", (double)OMX_BPM_MIN },
  { "BUS_INPUT_CAP", (double)OMX_BUS_INPUT_CAP },
  { "CENTRE_WINDOW_HALF_WIDTH", (double)OMX_CENTRE_WINDOW_HALF_WIDTH },
  { "CHAIN_INPUT", (double)OMX_CHAIN_INPUT },
  { "CHANNEL_CONFIG_SCHEMA_VERSION", (double)OMX_CHANNEL_CONFIG_SCHEMA_VERSION },
  { "CONTINUOUS", (double)OMX_CONTINUOUS },
  { "CONTRACT_VERSION_MAJOR", (double)OMX_CONTRACT_VERSION_MAJOR },
  { "CONTRACT_VERSION_MINOR", (double)OMX_CONTRACT_VERSION_MINOR },
  { "CYCLE_FIXED_NS_176400", (double)OMX_CYCLE_FIXED_NS_176400 },
  { "CYCLE_FIXED_NS_192000", (double)OMX_CYCLE_FIXED_NS_192000 },
  { "CYCLE_FIXED_NS_44100", (double)OMX_CYCLE_FIXED_NS_44100 },
  { "CYCLE_FIXED_NS_48000", (double)OMX_CYCLE_FIXED_NS_48000 },
  { "CYCLE_FIXED_NS_88200", (double)OMX_CYCLE_FIXED_NS_88200 },
  { "CYCLE_FIXED_NS_96000", (double)OMX_CYCLE_FIXED_NS_96000 },
  { "DEEP_PLATEAU_FRAMES", (double)OMX_DEEP_PLATEAU_FRAMES },
  { "DEESS_KNEE_DB", (double)OMX_DEESS_KNEE_DB },
  { "DEFAULT_BAND_HIGH_HZ", (double)OMX_DEFAULT_BAND_HIGH_HZ },
  { "DEFAULT_BAND_LOW_HZ", (double)OMX_DEFAULT_BAND_LOW_HZ },
  { "DEFAULT_FADE_FRACTION", (double)OMX_DEFAULT_FADE_FRACTION },
  { "DEFAULT_FREQ_HZ", (double)OMX_DEFAULT_FREQ_HZ },
  { "DEFAULT_HEAD_AMP_GAIN_DB", (double)OMX_DEFAULT_HEAD_AMP_GAIN_DB },
  { "DEFAULT_INPUT_CHANNELS", (double)OMX_DEFAULT_INPUT_CHANNELS },
  { "DEFAULT_LATENCY_BUDGET_MS_EFFECTS", (double)OMX_DEFAULT_LATENCY_BUDGET_MS_EFFECTS },
  { "DEFAULT_LATENCY_BUDGET_MS_MONITOR", (double)OMX_DEFAULT_LATENCY_BUDGET_MS_MONITOR },
  { "DEFAULT_LATENCY_BUDGET_MS_PROGRAM", (double)OMX_DEFAULT_LATENCY_BUDGET_MS_PROGRAM },
  { "DEFAULT_LEVEL", (double)OMX_DEFAULT_LEVEL },
  { "DEFAULT_PRESET_INPUTS", (double)OMX_DEFAULT_PRESET_INPUTS },
  { "DEFAULT_PRESET_OUTPUTS", (double)OMX_DEFAULT_PRESET_OUTPUTS },
  { "DEFAULT_THRESHOLDS_GROWTH_CONFIRM_FRAMES", (double)OMX_DEFAULT_THRESHOLDS_GROWTH_CONFIRM_FRAMES },
  { "DEFAULT_THRESHOLDS_GROWTH_MAX_DIP_DB", (double)OMX_DEFAULT_THRESHOLDS_GROWTH_MAX_DIP_DB },
  { "DEFAULT_THRESHOLDS_GROWTH_MAX_SINGLE_FRAME_SHARE", (double)OMX_DEFAULT_THRESHOLDS_GROWTH_MAX_SINGLE_FRAME_SHARE },
  { "DEFAULT_THRESHOLDS_GROWTH_MIN_DB_PER_FRAME", (double)OMX_DEFAULT_THRESHOLDS_GROWTH_MIN_DB_PER_FRAME },
  { "DEFAULT_THRESHOLDS_GROWTH_MIN_TOTAL_RISE_DB", (double)OMX_DEFAULT_THRESHOLDS_GROWTH_MIN_TOTAL_RISE_DB },
  { "DEFAULT_THRESHOLDS_PAPR_DB", (double)OMX_DEFAULT_THRESHOLDS_PAPR_DB },
  { "DEFAULT_THRESHOLDS_PERSIST_FRAMES", (double)OMX_DEFAULT_THRESHOLDS_PERSIST_FRAMES },
  { "DEFAULT_THRESHOLDS_PHPR_DB", (double)OMX_DEFAULT_THRESHOLDS_PHPR_DB },
  { "DEFAULT_THRESHOLDS_PNPR_DB", (double)OMX_DEFAULT_THRESHOLDS_PNPR_DB },
  { "DEFAULT_THRESHOLDS_PSHR_MIN_DB", (double)OMX_DEFAULT_THRESHOLDS_PSHR_MIN_DB },
  { "DEFAULT_THRESHOLDS_SUB_CLEAN_FRAMES", (double)OMX_DEFAULT_THRESHOLDS_SUB_CLEAN_FRAMES },
  { "DEFAULT_WEB_PORT", (double)OMX_DEFAULT_WEB_PORT },
  { "DESK_GAIN_RANGE_MAX_DB", (double)OMX_DESK_GAIN_RANGE_MAX_DB },
  { "DESK_GAIN_RANGE_MIN_DB", (double)OMX_DESK_GAIN_RANGE_MIN_DB },
  { "DESK_GAIN_RANGE_STEP_DB", (double)OMX_DESK_GAIN_RANGE_STEP_DB },
  { "DETECTOR_OVERSAMPLE_AUTO_MS", (double)OMX_DETECTOR_OVERSAMPLE_AUTO_MS },
  { "DETECTOR_OVERSAMPLE_LATENCY_SAMPLES", (double)OMX_DETECTOR_OVERSAMPLE_LATENCY_SAMPLES },
  { "DIVERGENCE_RANGE_MAX", (double)OMX_DIVERGENCE_RANGE_MAX },
  { "DIVERGENCE_RANGE_MIN", (double)OMX_DIVERGENCE_RANGE_MIN },
  { "DIVERGENCE_RANGE_STEP", (double)OMX_DIVERGENCE_RANGE_STEP },
  { "DRIVE_BIAS_MAX", (double)OMX_DRIVE_BIAS_MAX },
  { "EARLY_REFLECTION_FLOOR_DB", (double)OMX_EARLY_REFLECTION_FLOOR_DB },
  { "EARLY_REFLECTION_WINDOW_MS", (double)OMX_EARLY_REFLECTION_WINDOW_MS },
  { "EQ_DEFAULT_SAMPLE_RATE", (double)OMX_EQ_DEFAULT_SAMPLE_RATE },
  { "EQ_FREQ_RANGE_MAX", (double)OMX_EQ_FREQ_RANGE_MAX },
  { "EQ_FREQ_RANGE_MIN", (double)OMX_EQ_FREQ_RANGE_MIN },
  { "EQ_FREQ_RANGE_STEP", (double)OMX_EQ_FREQ_RANGE_STEP },
  { "EQ_GAIN_LIMIT_DB", (double)OMX_EQ_GAIN_LIMIT_DB },
  { "EQ_GAIN_RANGE_MAX", (double)OMX_EQ_GAIN_RANGE_MAX },
  { "EQ_GAIN_RANGE_MIN", (double)OMX_EQ_GAIN_RANGE_MIN },
  { "EQ_GAIN_RANGE_STEP", (double)OMX_EQ_GAIN_RANGE_STEP },
  { "EQ_MAX_BANDS", (double)OMX_EQ_MAX_BANDS },
  { "EQ_NOTCH_Q_RANGE_MAX", (double)OMX_EQ_NOTCH_Q_RANGE_MAX },
  { "EQ_NOTCH_Q_RANGE_MIN", (double)OMX_EQ_NOTCH_Q_RANGE_MIN },
  { "EQ_NOTCH_Q_RANGE_STEP", (double)OMX_EQ_NOTCH_Q_RANGE_STEP },
  { "EQ_Q_RANGE_MAX", (double)OMX_EQ_Q_RANGE_MAX },
  { "EQ_Q_RANGE_MIN", (double)OMX_EQ_Q_RANGE_MIN },
  { "EQ_Q_RANGE_STEP", (double)OMX_EQ_Q_RANGE_STEP },
  { "FAMILY_COMP_RATIO_BOUNDS_BASS_MAX", (double)OMX_FAMILY_COMP_RATIO_BOUNDS_BASS_MAX },
  { "FAMILY_COMP_RATIO_BOUNDS_BASS_MIN", (double)OMX_FAMILY_COMP_RATIO_BOUNDS_BASS_MIN },
  { "FAMILY_COMP_RATIO_BOUNDS_BRASS_MAX", (double)OMX_FAMILY_COMP_RATIO_BOUNDS_BRASS_MAX },
  { "FAMILY_COMP_RATIO_BOUNDS_BRASS_MIN", (double)OMX_FAMILY_COMP_RATIO_BOUNDS_BRASS_MIN },
  { "FAMILY_COMP_RATIO_BOUNDS_DRUMS_MAX", (double)OMX_FAMILY_COMP_RATIO_BOUNDS_DRUMS_MAX },
  { "FAMILY_COMP_RATIO_BOUNDS_DRUMS_MIN", (double)OMX_FAMILY_COMP_RATIO_BOUNDS_DRUMS_MIN },
  { "FAMILY_COMP_RATIO_BOUNDS_GUITAR_MAX", (double)OMX_FAMILY_COMP_RATIO_BOUNDS_GUITAR_MAX },
  { "FAMILY_COMP_RATIO_BOUNDS_GUITAR_MIN", (double)OMX_FAMILY_COMP_RATIO_BOUNDS_GUITAR_MIN },
  { "FAMILY_COMP_RATIO_BOUNDS_KEYS_MAX", (double)OMX_FAMILY_COMP_RATIO_BOUNDS_KEYS_MAX },
  { "FAMILY_COMP_RATIO_BOUNDS_KEYS_MIN", (double)OMX_FAMILY_COMP_RATIO_BOUNDS_KEYS_MIN },
  { "FAMILY_COMP_RATIO_BOUNDS_PERCUSSION_MAX", (double)OMX_FAMILY_COMP_RATIO_BOUNDS_PERCUSSION_MAX },
  { "FAMILY_COMP_RATIO_BOUNDS_PERCUSSION_MIN", (double)OMX_FAMILY_COMP_RATIO_BOUNDS_PERCUSSION_MIN },
  { "FAMILY_COMP_RATIO_BOUNDS_PLAYBACK_MAX", (double)OMX_FAMILY_COMP_RATIO_BOUNDS_PLAYBACK_MAX },
  { "FAMILY_COMP_RATIO_BOUNDS_PLAYBACK_MIN", (double)OMX_FAMILY_COMP_RATIO_BOUNDS_PLAYBACK_MIN },
  { "FAMILY_COMP_RATIO_BOUNDS_STRINGS_MAX", (double)OMX_FAMILY_COMP_RATIO_BOUNDS_STRINGS_MAX },
  { "FAMILY_COMP_RATIO_BOUNDS_STRINGS_MIN", (double)OMX_FAMILY_COMP_RATIO_BOUNDS_STRINGS_MIN },
  { "FAMILY_COMP_RATIO_BOUNDS_VOCALS_MAX", (double)OMX_FAMILY_COMP_RATIO_BOUNDS_VOCALS_MAX },
  { "FAMILY_COMP_RATIO_BOUNDS_VOCALS_MIN", (double)OMX_FAMILY_COMP_RATIO_BOUNDS_VOCALS_MIN },
  { "FAMILY_COMP_RATIO_BOUNDS_WIND_MAX", (double)OMX_FAMILY_COMP_RATIO_BOUNDS_WIND_MAX },
  { "FAMILY_COMP_RATIO_BOUNDS_WIND_MIN", (double)OMX_FAMILY_COMP_RATIO_BOUNDS_WIND_MIN },
  { "FBS_AUTO_BANDS_RANGE_MAX", (double)OMX_FBS_AUTO_BANDS_RANGE_MAX },
  { "FBS_AUTO_BANDS_RANGE_MIN", (double)OMX_FBS_AUTO_BANDS_RANGE_MIN },
  { "FBS_AUTO_BANDS_RANGE_STEP", (double)OMX_FBS_AUTO_BANDS_RANGE_STEP },
  { "FBS_COOLDOWN_MINUTES_RANGE_MAX", (double)OMX_FBS_COOLDOWN_MINUTES_RANGE_MAX },
  { "FBS_COOLDOWN_MINUTES_RANGE_MIN", (double)OMX_FBS_COOLDOWN_MINUTES_RANGE_MIN },
  { "FBS_COOLDOWN_MINUTES_RANGE_STEP", (double)OMX_FBS_COOLDOWN_MINUTES_RANGE_STEP },
  { "FBS_DEFAULT_COOLDOWN_MINUTES", (double)OMX_FBS_DEFAULT_COOLDOWN_MINUTES },
  { "FBS_DEFAULT_HOLD_SECONDS", (double)OMX_FBS_DEFAULT_HOLD_SECONDS },
  { "FBS_DEFAULT_MAX_AUTO_BANDS", (double)OMX_FBS_DEFAULT_MAX_AUTO_BANDS },
  { "FBS_DEFAULT_MERGE_CENTS", (double)OMX_FBS_DEFAULT_MERGE_CENTS },
  { "FBS_DEFAULT_NOTCH_Q", (double)OMX_FBS_DEFAULT_NOTCH_Q },
  { "FBS_DEFAULT_SENSITIVITY", (double)OMX_FBS_DEFAULT_SENSITIVITY },
  { "FBS_FLOOR_LIN", (double)OMX_FBS_FLOOR_LIN },
  { "FBS_HOLD_SECONDS_RANGE_MAX", (double)OMX_FBS_HOLD_SECONDS_RANGE_MAX },
  { "FBS_HOLD_SECONDS_RANGE_MIN", (double)OMX_FBS_HOLD_SECONDS_RANGE_MIN },
  { "FBS_HOLD_SECONDS_RANGE_STEP", (double)OMX_FBS_HOLD_SECONDS_RANGE_STEP },
  { "FBS_LIFT_RAMP_MS", (double)OMX_FBS_LIFT_RAMP_MS },
  { "FBS_MAX_CUT_DB", (double)OMX_FBS_MAX_CUT_DB },
  { "FBS_MAX_NOTCH_DEPTH_DB", (double)OMX_FBS_MAX_NOTCH_DEPTH_DB },
  { "FBS_MERGE_CENTS_RANGE_MAX", (double)OMX_FBS_MERGE_CENTS_RANGE_MAX },
  { "FBS_MERGE_CENTS_RANGE_MIN", (double)OMX_FBS_MERGE_CENTS_RANGE_MIN },
  { "FBS_MERGE_CENTS_RANGE_STEP", (double)OMX_FBS_MERGE_CENTS_RANGE_STEP },
  { "FBS_PAPR_GUARD_BINS", (double)OMX_FBS_PAPR_GUARD_BINS },
  { "FBS_PHPR_HARMONICS", (double)OMX_FBS_PHPR_HARMONICS },
  { "FBS_PNPR_GUARD_BINS", (double)OMX_FBS_PNPR_GUARD_BINS },
  { "FBS_PNPR_RADIUS_BINS", (double)OMX_FBS_PNPR_RADIUS_BINS },
  { "FBS_PSHR_SELF_SKIP_BINS", (double)OMX_FBS_PSHR_SELF_SKIP_BINS },
  { "FBS_RECLAMP_BACKOFF_CAP", (double)OMX_FBS_RECLAMP_BACKOFF_CAP },
  { "FBS_RECLAMP_DEEPEN_DB", (double)OMX_FBS_RECLAMP_DEEPEN_DB },
  { "FBS_RELEASE_DONE_DB", (double)OMX_FBS_RELEASE_DONE_DB },
  { "FBS_RELEASE_DWELL_MS", (double)OMX_FBS_RELEASE_DWELL_MS },
  { "FBS_RELEASE_RATIO", (double)OMX_FBS_RELEASE_RATIO },
  { "FBS_RING_HZ_MAX", (double)OMX_FBS_RING_HZ_MAX },
  { "FBS_RING_HZ_MIN", (double)OMX_FBS_RING_HZ_MIN },
  { "FBS_SENSITIVITY_RANGE_MAX", (double)OMX_FBS_SENSITIVITY_RANGE_MAX },
  { "FBS_SENSITIVITY_RANGE_MIN", (double)OMX_FBS_SENSITIVITY_RANGE_MIN },
  { "FBS_SENSITIVITY_RANGE_STEP", (double)OMX_FBS_SENSITIVITY_RANGE_STEP },
  { "FBS_TRACK_SLOTS", (double)OMX_FBS_TRACK_SLOTS },
  { "FDELAY_MOD_READ_ORDER", (double)OMX_FDELAY_MOD_READ_ORDER },
  { "FDELAY_READ_L1_NORM", (double)OMX_FDELAY_READ_L1_NORM },
  { "GATE_KEY_VOICE_BAND_HP_HZ", (double)OMX_GATE_KEY_VOICE_BAND_HP_HZ },
  { "GATE_KEY_VOICE_BAND_LP_HZ", (double)OMX_GATE_KEY_VOICE_BAND_LP_HZ },
  { "GATE_RANGE_FLOOR_DB", (double)OMX_GATE_RANGE_FLOOR_DB },
  { "GEQ_BANDS", (double)OMX_GEQ_BANDS },
  { "GEQ_BAND_Q", (double)OMX_GEQ_BAND_Q },
  { "GROWTH_CONFIRM_FRAMES", (double)OMX_GROWTH_CONFIRM_FRAMES },
  { "GROWTH_MAX_DIP_DB", (double)OMX_GROWTH_MAX_DIP_DB },
  { "GROWTH_MAX_SINGLE_FRAME_SHARE", (double)OMX_GROWTH_MAX_SINGLE_FRAME_SHARE },
  { "GROWTH_MIN_DB_PER_FRAME", (double)OMX_GROWTH_MIN_DB_PER_FRAME },
  { "GROWTH_MIN_TOTAL_RISE_DB", (double)OMX_GROWTH_MIN_TOTAL_RISE_DB },
  { "GROWTH_WINDOW_FRAMES", (double)OMX_GROWTH_WINDOW_FRAMES },
  { "HEAD_AMP_GAIN_MAX_DB", (double)OMX_HEAD_AMP_GAIN_MAX_DB },
  { "HEAD_AMP_GAIN_MIN_DB", (double)OMX_HEAD_AMP_GAIN_MIN_DB },
  { "HOSTED_STAGE_CLAMP_DBFS", (double)OMX_HOSTED_STAGE_CLAMP_DBFS },
  { "HOSTED_STAGE_EVENTS_PER_BLOCK", (double)OMX_HOSTED_STAGE_EVENTS_PER_BLOCK },
  { "HOSTED_STAGE_NON_FINITE_STRIKES", (double)OMX_HOSTED_STAGE_NON_FINITE_STRIKES },
  { "HOSTED_STAGE_PARAM_QUEUE_DEPTH", (double)OMX_HOSTED_STAGE_PARAM_QUEUE_DEPTH },
  { "HOSTED_STAGE_UNPUBLISH_POLL_US", (double)OMX_HOSTED_STAGE_UNPUBLISH_POLL_US },
  { "HOSTED_STAGE_UNPUBLISH_TIMEOUT_US", (double)OMX_HOSTED_STAGE_UNPUBLISH_TIMEOUT_US },
  { "HOSTED_STAGE_WARMUP_BLOCKS", (double)OMX_HOSTED_STAGE_WARMUP_BLOCKS },
  { "HOSTED_STAGE_WARMUP_LEVEL_DBFS", (double)OMX_HOSTED_STAGE_WARMUP_LEVEL_DBFS },
  { "HOSTED_STAGE_WORKER_POLL_US", (double)OMX_HOSTED_STAGE_WORKER_POLL_US },
  { "HOSTED_STAGE_WORKER_RING_BYTES", (double)OMX_HOSTED_STAGE_WORKER_RING_BYTES },
  { "HPF_FREQ_RANGE_MAX", (double)OMX_HPF_FREQ_RANGE_MAX },
  { "HPF_FREQ_RANGE_MIN", (double)OMX_HPF_FREQ_RANGE_MIN },
  { "HPF_FREQ_RANGE_STEP", (double)OMX_HPF_FREQ_RANGE_STEP },
  { "HRP_AMOUNT_RANGE_MAX", (double)OMX_HRP_AMOUNT_RANGE_MAX },
  { "HRP_AMOUNT_RANGE_MIN", (double)OMX_HRP_AMOUNT_RANGE_MIN },
  { "HRP_AMOUNT_RANGE_STEP", (double)OMX_HRP_AMOUNT_RANGE_STEP },
  { "HRP_ATTRIBUTION_CENTS", (double)OMX_HRP_ATTRIBUTION_CENTS },
  { "HRP_AUTO_BANDS_RANGE_MAX", (double)OMX_HRP_AUTO_BANDS_RANGE_MAX },
  { "HRP_AUTO_BANDS_RANGE_MIN", (double)OMX_HRP_AUTO_BANDS_RANGE_MIN },
  { "HRP_AUTO_BANDS_RANGE_STEP", (double)OMX_HRP_AUTO_BANDS_RANGE_STEP },
  { "HRP_BAND_Q", (double)OMX_HRP_BAND_Q },
  { "HRP_COLLISION_CENTS", (double)OMX_HRP_COLLISION_CENTS },
  { "HRP_DEFAULT_MAX_AUTO_BANDS", (double)OMX_HRP_DEFAULT_MAX_AUTO_BANDS },
  { "HRP_EXCESS_THRESHOLD_DB", (double)OMX_HRP_EXCESS_THRESHOLD_DB },
  { "HRP_FAMILY_SEARCH_BASS_F0_MAX_HZ", (double)OMX_HRP_FAMILY_SEARCH_BASS_F0_MAX_HZ },
  { "HRP_FAMILY_SEARCH_BASS_F0_MIN_HZ", (double)OMX_HRP_FAMILY_SEARCH_BASS_F0_MIN_HZ },
  { "HRP_FAMILY_SEARCH_BASS_MAX_VOICES", (double)OMX_HRP_FAMILY_SEARCH_BASS_MAX_VOICES },
  { "HRP_FAMILY_SEARCH_BRASS_F0_MAX_HZ", (double)OMX_HRP_FAMILY_SEARCH_BRASS_F0_MAX_HZ },
  { "HRP_FAMILY_SEARCH_BRASS_F0_MIN_HZ", (double)OMX_HRP_FAMILY_SEARCH_BRASS_F0_MIN_HZ },
  { "HRP_FAMILY_SEARCH_BRASS_MAX_VOICES", (double)OMX_HRP_FAMILY_SEARCH_BRASS_MAX_VOICES },
  { "HRP_FAMILY_SEARCH_DRUMS_F0_MAX_HZ", (double)OMX_HRP_FAMILY_SEARCH_DRUMS_F0_MAX_HZ },
  { "HRP_FAMILY_SEARCH_DRUMS_F0_MIN_HZ", (double)OMX_HRP_FAMILY_SEARCH_DRUMS_F0_MIN_HZ },
  { "HRP_FAMILY_SEARCH_DRUMS_MAX_VOICES", (double)OMX_HRP_FAMILY_SEARCH_DRUMS_MAX_VOICES },
  { "HRP_FAMILY_SEARCH_GUITAR_F0_MAX_HZ", (double)OMX_HRP_FAMILY_SEARCH_GUITAR_F0_MAX_HZ },
  { "HRP_FAMILY_SEARCH_GUITAR_F0_MIN_HZ", (double)OMX_HRP_FAMILY_SEARCH_GUITAR_F0_MIN_HZ },
  { "HRP_FAMILY_SEARCH_GUITAR_MAX_VOICES", (double)OMX_HRP_FAMILY_SEARCH_GUITAR_MAX_VOICES },
  { "HRP_FAMILY_SEARCH_KEYS_F0_MAX_HZ", (double)OMX_HRP_FAMILY_SEARCH_KEYS_F0_MAX_HZ },
  { "HRP_FAMILY_SEARCH_KEYS_F0_MIN_HZ", (double)OMX_HRP_FAMILY_SEARCH_KEYS_F0_MIN_HZ },
  { "HRP_FAMILY_SEARCH_KEYS_MAX_VOICES", (double)OMX_HRP_FAMILY_SEARCH_KEYS_MAX_VOICES },
  { "HRP_FAMILY_SEARCH_PERCUSSION_F0_MAX_HZ", (double)OMX_HRP_FAMILY_SEARCH_PERCUSSION_F0_MAX_HZ },
  { "HRP_FAMILY_SEARCH_PERCUSSION_F0_MIN_HZ", (double)OMX_HRP_FAMILY_SEARCH_PERCUSSION_F0_MIN_HZ },
  { "HRP_FAMILY_SEARCH_PERCUSSION_MAX_VOICES", (double)OMX_HRP_FAMILY_SEARCH_PERCUSSION_MAX_VOICES },
  { "HRP_FAMILY_SEARCH_PLAYBACK_F0_MAX_HZ", (double)OMX_HRP_FAMILY_SEARCH_PLAYBACK_F0_MAX_HZ },
  { "HRP_FAMILY_SEARCH_PLAYBACK_F0_MIN_HZ", (double)OMX_HRP_FAMILY_SEARCH_PLAYBACK_F0_MIN_HZ },
  { "HRP_FAMILY_SEARCH_PLAYBACK_MAX_VOICES", (double)OMX_HRP_FAMILY_SEARCH_PLAYBACK_MAX_VOICES },
  { "HRP_FAMILY_SEARCH_STRINGS_F0_MAX_HZ", (double)OMX_HRP_FAMILY_SEARCH_STRINGS_F0_MAX_HZ },
  { "HRP_FAMILY_SEARCH_STRINGS_F0_MIN_HZ", (double)OMX_HRP_FAMILY_SEARCH_STRINGS_F0_MIN_HZ },
  { "HRP_FAMILY_SEARCH_STRINGS_MAX_VOICES", (double)OMX_HRP_FAMILY_SEARCH_STRINGS_MAX_VOICES },
  { "HRP_FAMILY_SEARCH_VOCALS_F0_MAX_HZ", (double)OMX_HRP_FAMILY_SEARCH_VOCALS_F0_MAX_HZ },
  { "HRP_FAMILY_SEARCH_VOCALS_F0_MIN_HZ", (double)OMX_HRP_FAMILY_SEARCH_VOCALS_F0_MIN_HZ },
  { "HRP_FAMILY_SEARCH_VOCALS_MAX_VOICES", (double)OMX_HRP_FAMILY_SEARCH_VOCALS_MAX_VOICES },
  { "HRP_FAMILY_SEARCH_WIND_F0_MAX_HZ", (double)OMX_HRP_FAMILY_SEARCH_WIND_F0_MAX_HZ },
  { "HRP_FAMILY_SEARCH_WIND_F0_MIN_HZ", (double)OMX_HRP_FAMILY_SEARCH_WIND_F0_MIN_HZ },
  { "HRP_FAMILY_SEARCH_WIND_MAX_VOICES", (double)OMX_HRP_FAMILY_SEARCH_WIND_MAX_VOICES },
  { "HRP_GAIN_STEP_DB", (double)OMX_HRP_GAIN_STEP_DB },
  { "HRP_HARMONIC_COUNT", (double)OMX_HRP_HARMONIC_COUNT },
  { "HRP_MAX_BOOST_DB", (double)OMX_HRP_MAX_BOOST_DB },
  { "HRP_MAX_CUT_DB", (double)OMX_HRP_MAX_CUT_DB },
  { "HRP_MAX_VOICES", (double)OMX_HRP_MAX_VOICES },
  { "HRP_TIER_CROSSOVER_HZ", (double)OMX_HRP_TIER_CROSSOVER_HZ },
  { "INPUT_ALIGN_DELAY_RANGE_MAX", (double)OMX_INPUT_ALIGN_DELAY_RANGE_MAX },
  { "INPUT_ALIGN_DELAY_RANGE_MIN", (double)OMX_INPUT_ALIGN_DELAY_RANGE_MIN },
  { "INPUT_ALIGN_DELAY_RANGE_STEP", (double)OMX_INPUT_ALIGN_DELAY_RANGE_STEP },
  { "JOIN_LANE_NS_176400", (double)OMX_JOIN_LANE_NS_176400 },
  { "JOIN_LANE_NS_192000", (double)OMX_JOIN_LANE_NS_192000 },
  { "JOIN_LANE_NS_44100", (double)OMX_JOIN_LANE_NS_44100 },
  { "JOIN_LANE_NS_48000", (double)OMX_JOIN_LANE_NS_48000 },
  { "JOIN_LANE_NS_88200", (double)OMX_JOIN_LANE_NS_88200 },
  { "JOIN_LANE_NS_96000", (double)OMX_JOIN_LANE_NS_96000 },
  { "LANE_WALK_NS_176400", (double)OMX_LANE_WALK_NS_176400 },
  { "LANE_WALK_NS_192000", (double)OMX_LANE_WALK_NS_192000 },
  { "LANE_WALK_NS_44100", (double)OMX_LANE_WALK_NS_44100 },
  { "LANE_WALK_NS_48000", (double)OMX_LANE_WALK_NS_48000 },
  { "LANE_WALK_NS_88200", (double)OMX_LANE_WALK_NS_88200 },
  { "LANE_WALK_NS_96000", (double)OMX_LANE_WALK_NS_96000 },
  { "LPF_FREQ_RANGE_MAX", (double)OMX_LPF_FREQ_RANGE_MAX },
  { "LPF_FREQ_RANGE_MIN", (double)OMX_LPF_FREQ_RANGE_MIN },
  { "LPF_FREQ_RANGE_STEP", (double)OMX_LPF_FREQ_RANGE_STEP },
  { "MACHINE_BANDS_RANGE_MAX", (double)OMX_MACHINE_BANDS_RANGE_MAX },
  { "MACHINE_BANDS_RANGE_MIN", (double)OMX_MACHINE_BANDS_RANGE_MIN },
  { "MACHINE_BANDS_RANGE_STEP", (double)OMX_MACHINE_BANDS_RANGE_STEP },
  { "MAX_FREQ_HZ", (double)OMX_MAX_FREQ_HZ },
  { "MAX_INPUT_CHANNELS", (double)OMX_MAX_INPUT_CHANNELS },
  { "MAX_SYNC_DIVISION", (double)OMX_MAX_SYNC_DIVISION },
  { "METER_FLAG_LIMIT_MAX", (double)OMX_METER_FLAG_LIMIT_MAX },
  { "METER_FLAG_LIMIT_MIN", (double)OMX_METER_FLAG_LIMIT_MIN },
  { "METER_FLAG_LIMIT_STEP", (double)OMX_METER_FLAG_LIMIT_STEP },
  { "METER_FLOOR_DB", (double)OMX_METER_FLOOR_DB },
  { "METER_LEVEL_LIMIT_MAX", (double)OMX_METER_LEVEL_LIMIT_MAX },
  { "METER_LEVEL_LIMIT_MIN", (double)OMX_METER_LEVEL_LIMIT_MIN },
  { "METER_LEVEL_LIMIT_STEP", (double)OMX_METER_LEVEL_LIMIT_STEP },
  { "METER_REDUCTION_LIMIT_MAX", (double)OMX_METER_REDUCTION_LIMIT_MAX },
  { "METER_REDUCTION_LIMIT_MIN", (double)OMX_METER_REDUCTION_LIMIT_MIN },
  { "METER_REDUCTION_LIMIT_STEP", (double)OMX_METER_REDUCTION_LIMIT_STEP },
  { "METER_RELEASE_PER_FRAME", (double)OMX_METER_RELEASE_PER_FRAME },
  { "METER_STEP_HYSTERESIS", (double)OMX_METER_STEP_HYSTERESIS },
  { "MIN_FRAMES", (double)OMX_MIN_FRAMES },
  { "MIN_FREQ_HZ", (double)OMX_MIN_FREQ_HZ },
  { "MIN_INPUT_CHANNELS", (double)OMX_MIN_INPUT_CHANNELS },
  { "MIN_SYNC_DIVISION", (double)OMX_MIN_SYNC_DIVISION },
  { "MONO_FOLD_COEF", (double)OMX_MONO_FOLD_COEF },
  { "NATIVE_INSERT_STAGE", (double)OMX_NATIVE_INSERT_STAGE },
  { "NATIVE_STAGE_ID_CHORUS", (double)OMX_NATIVE_STAGE_ID_CHORUS },
  { "NATIVE_STAGE_ID_DELAY", (double)OMX_NATIVE_STAGE_ID_DELAY },
  { "NATIVE_STAGE_ID_DE_ESSER", (double)OMX_NATIVE_STAGE_ID_DE_ESSER },
  { "NATIVE_STAGE_ID_DRIVE", (double)OMX_NATIVE_STAGE_ID_DRIVE },
  { "NATIVE_STAGE_ID_DYNAMICS", (double)OMX_NATIVE_STAGE_ID_DYNAMICS },
  { "NATIVE_STAGE_ID_EQ", (double)OMX_NATIVE_STAGE_ID_EQ },
  { "NATIVE_STAGE_ID_FLANGER", (double)OMX_NATIVE_STAGE_ID_FLANGER },
  { "NATIVE_STAGE_ID_GATE", (double)OMX_NATIVE_STAGE_ID_GATE },
  { "NATIVE_STAGE_ID_REVERB", (double)OMX_NATIVE_STAGE_ID_REVERB },
  { "NORMALIZED_RANGE_MAX", (double)OMX_NORMALIZED_RANGE_MAX },
  { "NORMALIZED_RANGE_MIN", (double)OMX_NORMALIZED_RANGE_MIN },
  { "NORMALIZED_RANGE_STEP", (double)OMX_NORMALIZED_RANGE_STEP },
  { "NO_BUSES_AUX", (double)OMX_NO_BUSES_AUX },
  { "NO_BUSES_DCA", (double)OMX_NO_BUSES_DCA },
  { "NO_BUSES_FX_RETURN", (double)OMX_NO_BUSES_FX_RETURN },
  { "NO_BUSES_GROUP", (double)OMX_NO_BUSES_GROUP },
  { "NO_BUSES_MAIN", (double)OMX_NO_BUSES_MAIN },
  { "NO_BUSES_MATRIX", (double)OMX_NO_BUSES_MATRIX },
  { "NO_BUSES_MIX_MINUS", (double)OMX_NO_BUSES_MIX_MINUS },
  { "OPERATOR_EQ_BANDS_RESERVE", (double)OMX_OPERATOR_EQ_BANDS_RESERVE },
  { "OSCILLATOR_FREQ_RANGE_MAX", (double)OMX_OSCILLATOR_FREQ_RANGE_MAX },
  { "OSCILLATOR_FREQ_RANGE_MIN", (double)OMX_OSCILLATOR_FREQ_RANGE_MIN },
  { "OSCILLATOR_FREQ_RANGE_STEP", (double)OMX_OSCILLATOR_FREQ_RANGE_STEP },
  { "OUTPUT_DELAY_RANGE_MAX", (double)OMX_OUTPUT_DELAY_RANGE_MAX },
  { "OUTPUT_DELAY_RANGE_MIN", (double)OMX_OUTPUT_DELAY_RANGE_MIN },
  { "OUTPUT_DELAY_RANGE_STEP", (double)OMX_OUTPUT_DELAY_RANGE_STEP },
  { "OUTPUT_TRIM_RANGE_MAX", (double)OMX_OUTPUT_TRIM_RANGE_MAX },
  { "OUTPUT_TRIM_RANGE_MIN", (double)OMX_OUTPUT_TRIM_RANGE_MIN },
  { "OUTPUT_TRIM_RANGE_STEP", (double)OMX_OUTPUT_TRIM_RANGE_STEP },
  { "PAN_RANGE_MAX", (double)OMX_PAN_RANGE_MAX },
  { "PAN_RANGE_MIN", (double)OMX_PAN_RANGE_MIN },
  { "PAN_RANGE_STEP", (double)OMX_PAN_RANGE_STEP },
  { "PATCH_SCHEMA_VERSION", (double)OMX_PATCH_SCHEMA_VERSION },
  { "PERF_REFRESH_LIMIT_MAX", (double)OMX_PERF_REFRESH_LIMIT_MAX },
  { "PERF_REFRESH_LIMIT_MIN", (double)OMX_PERF_REFRESH_LIMIT_MIN },
  { "PERF_REFRESH_LIMIT_STEP", (double)OMX_PERF_REFRESH_LIMIT_STEP },
  { "PITCH_PREFILTER_CEILING_HZ", (double)OMX_PITCH_PREFILTER_CEILING_HZ },
  { "PITCH_PREFILTER_Q", (double)OMX_PITCH_PREFILTER_Q },
  { "PITCH_WINDOW_MS", (double)OMX_PITCH_WINDOW_MS },
  { "PROGRAM_RELEASE_CHARGE_MS", (double)OMX_PROGRAM_RELEASE_CHARGE_MS },
  { "PROGRAM_RELEASE_DISCHARGE_MS", (double)OMX_PROGRAM_RELEASE_DISCHARGE_MS },
  { "PROGRAM_RELEASE_PROFILES_OPTO_FAST_MS", (double)OMX_PROGRAM_RELEASE_PROFILES_OPTO_FAST_MS },
  { "PROGRAM_RELEASE_PROFILES_OPTO_SHARE", (double)OMX_PROGRAM_RELEASE_PROFILES_OPTO_SHARE },
  { "PROGRAM_RELEASE_PROFILES_OPTO_SLOW_MAX_MS", (double)OMX_PROGRAM_RELEASE_PROFILES_OPTO_SLOW_MAX_MS },
  { "PROGRAM_RELEASE_PROFILES_OPTO_SLOW_MIN_MS", (double)OMX_PROGRAM_RELEASE_PROFILES_OPTO_SLOW_MIN_MS },
  { "PSHR_MIN_DB", (double)OMX_PSHR_MIN_DB },
  { "REAC_AUDIO_FABRIC_CEILING", (double)OMX_REAC_AUDIO_FABRIC_CEILING },
  { "REAC_AUDIO_FABRIC_SLOTS", (double)OMX_REAC_AUDIO_FABRIC_SLOTS },
  { "REAC_CFG_RATE_44100", (double)OMX_REAC_CFG_RATE_44100 },
  { "REAC_CFG_RATE_48000", (double)OMX_REAC_CFG_RATE_48000 },
  { "REAC_CFG_RATE_96000", (double)OMX_REAC_CFG_RATE_96000 },
  { "REAC_CFG_RATE_COUNT", (double)OMX_REAC_CFG_RATE_COUNT },
  { "REAC_CFG_ROLE_MASTER", (double)OMX_REAC_CFG_ROLE_MASTER },
  { "REAC_CFG_ROLE_SLAVE", (double)OMX_REAC_CFG_ROLE_SLAVE },
  { "REAC_HEADAMP_CEILING", (double)OMX_REAC_HEADAMP_CEILING },
  { "REAC_HEADAMP_RING", (double)OMX_REAC_HEADAMP_RING },
  { "REAC_HEADAMP_SLOTS", (double)OMX_REAC_HEADAMP_SLOTS },
  { "REAC_HEAD_AMP_GAIN_RANGE_MAX_DB", (double)OMX_REAC_HEAD_AMP_GAIN_RANGE_MAX_DB },
  { "REAC_HEAD_AMP_GAIN_RANGE_MIN_DB", (double)OMX_REAC_HEAD_AMP_GAIN_RANGE_MIN_DB },
  { "REAC_HEAD_AMP_GAIN_RANGE_STEP_DB", (double)OMX_REAC_HEAD_AMP_GAIN_RANGE_STEP_DB },
  { "REVERB_CUT_RANGE_MAX", (double)OMX_REVERB_CUT_RANGE_MAX },
  { "REVERB_CUT_RANGE_MIN", (double)OMX_REVERB_CUT_RANGE_MIN },
  { "REVERB_CUT_RANGE_STEP", (double)OMX_REVERB_CUT_RANGE_STEP },
  { "RME_PHONES_BALANCE_RANGE_MAX", (double)OMX_RME_PHONES_BALANCE_RANGE_MAX },
  { "RME_PHONES_BALANCE_RANGE_MIN", (double)OMX_RME_PHONES_BALANCE_RANGE_MIN },
  { "RME_PHONES_BALANCE_RANGE_STEP", (double)OMX_RME_PHONES_BALANCE_RANGE_STEP },
  { "RME_TRIM_RANGE_MAX", (double)OMX_RME_TRIM_RANGE_MAX },
  { "RME_TRIM_RANGE_MIN", (double)OMX_RME_TRIM_RANGE_MIN },
  { "RME_TRIM_RANGE_STEP", (double)OMX_RME_TRIM_RANGE_STEP },
  { "ROOM_MODE_BAND_HIGH_HZ", (double)OMX_ROOM_MODE_BAND_HIGH_HZ },
  { "ROOM_MODE_BAND_LOW_HZ", (double)OMX_ROOM_MODE_BAND_LOW_HZ },
  { "ROOM_MODE_MAX_CUT_DB", (double)OMX_ROOM_MODE_MAX_CUT_DB },
  { "ROOM_MODE_MIN_ABOVE_MEDIAN_DB", (double)OMX_ROOM_MODE_MIN_ABOVE_MEDIAN_DB },
  { "ROOM_MODE_MIN_POSITIONS", (double)OMX_ROOM_MODE_MIN_POSITIONS },
  { "ROTARY_BASE_MS", (double)OMX_ROTARY_BASE_MS },
  { "ROTARY_CROSSOVER_HZ", (double)OMX_ROTARY_CROSSOVER_HZ },
  { "ROTARY_DRUM_ACCEL_MS", (double)OMX_ROTARY_DRUM_ACCEL_MS },
  { "ROTARY_DRUM_AM", (double)OMX_ROTARY_DRUM_AM },
  { "ROTARY_DRUM_DECEL_MS", (double)OMX_ROTARY_DRUM_DECEL_MS },
  { "ROTARY_DRUM_DOPPLER_MS", (double)OMX_ROTARY_DRUM_DOPPLER_MS },
  { "ROTARY_HORN_ACCEL_MS", (double)OMX_ROTARY_HORN_ACCEL_MS },
  { "ROTARY_HORN_AM", (double)OMX_ROTARY_HORN_AM },
  { "ROTARY_HORN_DECEL_MS", (double)OMX_ROTARY_HORN_DECEL_MS },
  { "ROTARY_HORN_DOPPLER_MS", (double)OMX_ROTARY_HORN_DOPPLER_MS },
  { "ROTARY_RING_FLOATS", (double)OMX_ROTARY_RING_FLOATS },
  { "ROTARY_STOP_EPS", (double)OMX_ROTARY_STOP_EPS },
  { "RTA_FFT_SIZE_MAX", (double)OMX_RTA_FFT_SIZE_MAX },
  { "RTA_TAP_GATE_DB", (double)OMX_RTA_TAP_GATE_DB },
  { "RTA_TARGET_BIN_HZ", (double)OMX_RTA_TARGET_BIN_HZ },
  { "RT_ADMISSION_CEILING_RATIO", (double)OMX_RT_ADMISSION_CEILING_RATIO },
  { "RT_CAPACITY_TOLERANCE", (double)OMX_RT_CAPACITY_TOLERANCE },
  { "RT_HARD_TARGET_QUANTUM", (double)OMX_RT_HARD_TARGET_QUANTUM },
  { "RT_HARD_TARGET_RATE", (double)OMX_RT_HARD_TARGET_RATE },
  { "RT_HEADROOM_REFUSE_RATIO", (double)OMX_RT_HEADROOM_REFUSE_RATIO },
  { "RT_HEADROOM_WARN_RATIO", (double)OMX_RT_HEADROOM_WARN_RATIO },
  { "RT_PREDICTION_TOLERANCE", (double)OMX_RT_PREDICTION_TOLERANCE },
  { "RT_SPLIT_ECORE_WEIGHT_SEED", (double)OMX_RT_SPLIT_ECORE_WEIGHT_SEED },
  { "RT_STAGE_MAX_FACTOR", (double)OMX_RT_STAGE_MAX_FACTOR },
  { "SCENE_SCHEMA_VERSION", (double)OMX_SCENE_SCHEMA_VERSION },
  { "SEND_NS_PER_SAMPLE_176400", (double)OMX_SEND_NS_PER_SAMPLE_176400 },
  { "SEND_NS_PER_SAMPLE_192000", (double)OMX_SEND_NS_PER_SAMPLE_192000 },
  { "SEND_NS_PER_SAMPLE_44100", (double)OMX_SEND_NS_PER_SAMPLE_44100 },
  { "SEND_NS_PER_SAMPLE_48000", (double)OMX_SEND_NS_PER_SAMPLE_48000 },
  { "SEND_NS_PER_SAMPLE_88200", (double)OMX_SEND_NS_PER_SAMPLE_88200 },
  { "SEND_NS_PER_SAMPLE_96000", (double)OMX_SEND_NS_PER_SAMPLE_96000 },
  { "SENS_VALUE_MAX", (double)OMX_SENS_VALUE_MAX },
  { "SENS_VALUE_MIN", (double)OMX_SENS_VALUE_MIN },
  { "SESSION_SCHEMA_VERSION", (double)OMX_SESSION_SCHEMA_VERSION },
  { "SPEAKER_ALIGN_BAND_HIGH_HZ", (double)OMX_SPEAKER_ALIGN_BAND_HIGH_HZ },
  { "SPEAKER_ALIGN_BAND_LOW_HZ", (double)OMX_SPEAKER_ALIGN_BAND_LOW_HZ },
  { "SPECTRUM_LEVEL_LIMIT_MAX", (double)OMX_SPECTRUM_LEVEL_LIMIT_MAX },
  { "SPECTRUM_LEVEL_LIMIT_MIN", (double)OMX_SPECTRUM_LEVEL_LIMIT_MIN },
  { "SPECTRUM_LEVEL_LIMIT_STEP", (double)OMX_SPECTRUM_LEVEL_LIMIT_STEP },
  { "SPEED_OF_SOUND_M_S", (double)OMX_SPEED_OF_SOUND_M_S },
  { "STAGE_COST_NS_PER_SAMPLE_CHORUS_176400", (double)OMX_STAGE_COST_NS_PER_SAMPLE_CHORUS_176400 },
  { "STAGE_COST_NS_PER_SAMPLE_CHORUS_192000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_CHORUS_192000 },
  { "STAGE_COST_NS_PER_SAMPLE_CHORUS_44100", (double)OMX_STAGE_COST_NS_PER_SAMPLE_CHORUS_44100 },
  { "STAGE_COST_NS_PER_SAMPLE_CHORUS_48000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_CHORUS_48000 },
  { "STAGE_COST_NS_PER_SAMPLE_CHORUS_88200", (double)OMX_STAGE_COST_NS_PER_SAMPLE_CHORUS_88200 },
  { "STAGE_COST_NS_PER_SAMPLE_CHORUS_96000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_CHORUS_96000 },
  { "STAGE_COST_NS_PER_SAMPLE_DELAY_176400", (double)OMX_STAGE_COST_NS_PER_SAMPLE_DELAY_176400 },
  { "STAGE_COST_NS_PER_SAMPLE_DELAY_192000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_DELAY_192000 },
  { "STAGE_COST_NS_PER_SAMPLE_DELAY_44100", (double)OMX_STAGE_COST_NS_PER_SAMPLE_DELAY_44100 },
  { "STAGE_COST_NS_PER_SAMPLE_DELAY_48000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_DELAY_48000 },
  { "STAGE_COST_NS_PER_SAMPLE_DELAY_88200", (double)OMX_STAGE_COST_NS_PER_SAMPLE_DELAY_88200 },
  { "STAGE_COST_NS_PER_SAMPLE_DELAY_96000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_DELAY_96000 },
  { "STAGE_COST_NS_PER_SAMPLE_DE_ESSER_176400", (double)OMX_STAGE_COST_NS_PER_SAMPLE_DE_ESSER_176400 },
  { "STAGE_COST_NS_PER_SAMPLE_DE_ESSER_192000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_DE_ESSER_192000 },
  { "STAGE_COST_NS_PER_SAMPLE_DE_ESSER_44100", (double)OMX_STAGE_COST_NS_PER_SAMPLE_DE_ESSER_44100 },
  { "STAGE_COST_NS_PER_SAMPLE_DE_ESSER_48000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_DE_ESSER_48000 },
  { "STAGE_COST_NS_PER_SAMPLE_DE_ESSER_88200", (double)OMX_STAGE_COST_NS_PER_SAMPLE_DE_ESSER_88200 },
  { "STAGE_COST_NS_PER_SAMPLE_DE_ESSER_96000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_DE_ESSER_96000 },
  { "STAGE_COST_NS_PER_SAMPLE_DRIVE_176400", (double)OMX_STAGE_COST_NS_PER_SAMPLE_DRIVE_176400 },
  { "STAGE_COST_NS_PER_SAMPLE_DRIVE_192000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_DRIVE_192000 },
  { "STAGE_COST_NS_PER_SAMPLE_DRIVE_44100", (double)OMX_STAGE_COST_NS_PER_SAMPLE_DRIVE_44100 },
  { "STAGE_COST_NS_PER_SAMPLE_DRIVE_48000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_DRIVE_48000 },
  { "STAGE_COST_NS_PER_SAMPLE_DRIVE_88200", (double)OMX_STAGE_COST_NS_PER_SAMPLE_DRIVE_88200 },
  { "STAGE_COST_NS_PER_SAMPLE_DRIVE_96000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_DRIVE_96000 },
  { "STAGE_COST_NS_PER_SAMPLE_DYNAMICS_176400", (double)OMX_STAGE_COST_NS_PER_SAMPLE_DYNAMICS_176400 },
  { "STAGE_COST_NS_PER_SAMPLE_DYNAMICS_192000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_DYNAMICS_192000 },
  { "STAGE_COST_NS_PER_SAMPLE_DYNAMICS_44100", (double)OMX_STAGE_COST_NS_PER_SAMPLE_DYNAMICS_44100 },
  { "STAGE_COST_NS_PER_SAMPLE_DYNAMICS_48000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_DYNAMICS_48000 },
  { "STAGE_COST_NS_PER_SAMPLE_DYNAMICS_88200", (double)OMX_STAGE_COST_NS_PER_SAMPLE_DYNAMICS_88200 },
  { "STAGE_COST_NS_PER_SAMPLE_DYNAMICS_96000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_DYNAMICS_96000 },
  { "STAGE_COST_NS_PER_SAMPLE_EQ_176400", (double)OMX_STAGE_COST_NS_PER_SAMPLE_EQ_176400 },
  { "STAGE_COST_NS_PER_SAMPLE_EQ_192000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_EQ_192000 },
  { "STAGE_COST_NS_PER_SAMPLE_EQ_44100", (double)OMX_STAGE_COST_NS_PER_SAMPLE_EQ_44100 },
  { "STAGE_COST_NS_PER_SAMPLE_EQ_48000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_EQ_48000 },
  { "STAGE_COST_NS_PER_SAMPLE_EQ_88200", (double)OMX_STAGE_COST_NS_PER_SAMPLE_EQ_88200 },
  { "STAGE_COST_NS_PER_SAMPLE_EQ_96000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_EQ_96000 },
  { "STAGE_COST_NS_PER_SAMPLE_FLANGER_176400", (double)OMX_STAGE_COST_NS_PER_SAMPLE_FLANGER_176400 },
  { "STAGE_COST_NS_PER_SAMPLE_FLANGER_192000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_FLANGER_192000 },
  { "STAGE_COST_NS_PER_SAMPLE_FLANGER_44100", (double)OMX_STAGE_COST_NS_PER_SAMPLE_FLANGER_44100 },
  { "STAGE_COST_NS_PER_SAMPLE_FLANGER_48000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_FLANGER_48000 },
  { "STAGE_COST_NS_PER_SAMPLE_FLANGER_88200", (double)OMX_STAGE_COST_NS_PER_SAMPLE_FLANGER_88200 },
  { "STAGE_COST_NS_PER_SAMPLE_FLANGER_96000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_FLANGER_96000 },
  { "STAGE_COST_NS_PER_SAMPLE_GATE_176400", (double)OMX_STAGE_COST_NS_PER_SAMPLE_GATE_176400 },
  { "STAGE_COST_NS_PER_SAMPLE_GATE_192000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_GATE_192000 },
  { "STAGE_COST_NS_PER_SAMPLE_GATE_44100", (double)OMX_STAGE_COST_NS_PER_SAMPLE_GATE_44100 },
  { "STAGE_COST_NS_PER_SAMPLE_GATE_48000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_GATE_48000 },
  { "STAGE_COST_NS_PER_SAMPLE_GATE_88200", (double)OMX_STAGE_COST_NS_PER_SAMPLE_GATE_88200 },
  { "STAGE_COST_NS_PER_SAMPLE_GATE_96000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_GATE_96000 },
  { "STAGE_COST_NS_PER_SAMPLE_REVERB_176400", (double)OMX_STAGE_COST_NS_PER_SAMPLE_REVERB_176400 },
  { "STAGE_COST_NS_PER_SAMPLE_REVERB_192000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_REVERB_192000 },
  { "STAGE_COST_NS_PER_SAMPLE_REVERB_44100", (double)OMX_STAGE_COST_NS_PER_SAMPLE_REVERB_44100 },
  { "STAGE_COST_NS_PER_SAMPLE_REVERB_48000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_REVERB_48000 },
  { "STAGE_COST_NS_PER_SAMPLE_REVERB_88200", (double)OMX_STAGE_COST_NS_PER_SAMPLE_REVERB_88200 },
  { "STAGE_COST_NS_PER_SAMPLE_REVERB_96000", (double)OMX_STAGE_COST_NS_PER_SAMPLE_REVERB_96000 },
  { "STRIP_QUANTUM", (double)OMX_STRIP_QUANTUM },
  { "SUBHARMONIC_RADIUS_BINS", (double)OMX_SUBHARMONIC_RADIUS_BINS },
  { "SURFACE_BANK_WIDTH", (double)OMX_SURFACE_BANK_WIDTH },
  { "SYNC_NS_176400", (double)OMX_SYNC_NS_176400 },
  { "SYNC_NS_192000", (double)OMX_SYNC_NS_192000 },
  { "SYNC_NS_44100", (double)OMX_SYNC_NS_44100 },
  { "SYNC_NS_48000", (double)OMX_SYNC_NS_48000 },
  { "SYNC_NS_88200", (double)OMX_SYNC_NS_88200 },
  { "SYNC_NS_96000", (double)OMX_SYNC_NS_96000 },
  { "T20_LOWER_DB", (double)OMX_T20_LOWER_DB },
  { "T20_UPPER_DB", (double)OMX_T20_UPPER_DB },
  { "TAKE_RENDER_SCHEMA_VERSION", (double)OMX_TAKE_RENDER_SCHEMA_VERSION },
  { "TAKE_REVERSE_RENDER_SCHEMA_VERSION", (double)OMX_TAKE_REVERSE_RENDER_SCHEMA_VERSION },
  { "TAKE_SCHEMA_VERSION", (double)OMX_TAKE_SCHEMA_VERSION },
  { "TAPER_FLOOR_DB", (double)OMX_TAPER_FLOOR_DB },
  { "TAP_AT_CHAIN_INPUT", (double)OMX_TAP_AT_CHAIN_INPUT },
  { "TAP_RESET_MS", (double)OMX_TAP_RESET_MS },
  { "TAP_WINDOW", (double)OMX_TAP_WINDOW },
  { "TIER_CROSSOVER_HZ", (double)OMX_TIER_CROSSOVER_HZ },
  { "TRANSIENT_FAST_ATTACK_MS", (double)OMX_TRANSIENT_FAST_ATTACK_MS },
  { "TRANSIENT_FAST_RELEASE_MS", (double)OMX_TRANSIENT_FAST_RELEASE_MS },
  { "TRANSIENT_FLOOR_LIN", (double)OMX_TRANSIENT_FLOOR_LIN },
  { "TRANSIENT_REF_DB", (double)OMX_TRANSIENT_REF_DB },
  { "TRIM_RANGE_MAX_DB", (double)OMX_TRIM_RANGE_MAX_DB },
  { "TRIM_RANGE_MIN_DB", (double)OMX_TRIM_RANGE_MIN_DB },
  { "TRIM_RANGE_STEP_DB", (double)OMX_TRIM_RANGE_STEP_DB },
  { "UNITY_POSITION", (double)OMX_UNITY_POSITION },
  { "XOVER_LR2_SECTION_Q", (double)OMX_XOVER_LR2_SECTION_Q },
  { "XOVER_LR4_SECTION_Q", (double)OMX_XOVER_LR4_SECTION_Q },
  { "XOVER_PARTITION_TOLERANCE", (double)OMX_XOVER_PARTITION_TOLERANCE },
};
#define OMX_DECLARED_SCALAR_COUNT 445u
#endif

#endif /* OMX_CONTRACT_LIMITS_H */

/* The sample rates the console declares (core's STANDARD_SAMPLE_RATES, row-codecs.ts): the set a
 * contract's rate-is-declared precondition accepts, through omx_rate_is_declared(), and the grid a
 * native tool iterates. Guarded on its own so a tool built against a pinned copy of this header
 * (lv2-inprocess-pin.sh) can include this tree's copy after it and gain the rates without mixing
 * the pin's limits. */
#ifndef OMX_DECLARED_RATE_COUNT
#define OMX_DECLARED_RATE_COUNT 6u
static const float OMX_DECLARED_RATES[OMX_DECLARED_RATE_COUNT] = { 44100.0f, 48000.0f, 88200.0f, 96000.0f, 176400.0f, 192000.0f };
/* The declared rates that are whole multiples of `base` (a tool's default grid: the 48 kHz family),
 * in declaration order, at most `cap` of them; returns how many were written to `out`. */
static inline int omx_declared_rates_multiple_of(unsigned base, int *out, int cap) {
  int n = 0;
  for (unsigned k = 0; k < OMX_DECLARED_RATE_COUNT && n < cap; k++)
    if ((unsigned)OMX_DECLARED_RATES[k] % base == 0) out[n++] = (int)OMX_DECLARED_RATES[k];
  return n;
}
#endif
