#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Pau Aliagas <linuxnow@gmail.com>
#
# kernels-gen.sh <out-dir> — derives both omxdsp_suite.c's arm list and omxdsp_perturb.c's
# perturb-case list from test/kernels/ instead of a hand-appended call in each file's main().
#
# Two file shapes, collected separately, both sorted by filename for a deterministic build:
#   test/kernels/<name>.c          — one suite arm: `static void arm_<name>(void)`.
#   test/kernels/<name>.perturb.c  — one perturbation case: `static int perturb_<name>(int failed)`.
# A kernel lane adds ONE file of either shape and touches omxdsp_suite.c, omxdsp_perturb.c or
# this script NEVER. Output is a build artefact, never committed
# (docs/design/specs/2026-09-15-no-stored-derivations.md).
#
# Usage: tools/kernels-gen.sh <out-dir>
#   writes <out-dir>/kernels-suite.inc.c and <out-dir>/kernels-perturb.inc.c
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
PKG="$(cd "$HERE/.." && pwd)"
OUT="${1:?out dir}"
mkdir -p "$OUT"

sorted_glob() { # $1 = glob pattern (relative to $PKG/test/kernels), prints sorted absolute paths
  shopt -s nullglob
  local files=("$PKG"/test/kernels/$1)
  shopt -u nullglob
  if [ "${#files[@]}" -gt 0 ]; then printf '%s\n' "${files[@]}" | sort; fi
}

# ---- the suite arms: test/kernels/<name>.c, excluding *.perturb.c -------------------------------
mapfile -t suite_files < <(sorted_glob '*.c' | grep -v '\.perturb\.c$' || true)
if [ "${#suite_files[@]}" -eq 0 ]; then
  echo "kernels-gen.sh: no suite arm files found under test/kernels/" >&2
  exit 1
fi
dest_suite="$OUT/kernels-suite.inc.c"
{
  echo "/* GENERATED by tools/kernels-gen.sh from test/kernels/ (sorted by filename) — do not edit, not committed. */"
  names=()
  for f in "${suite_files[@]}"; do
    base="$(basename "$f" .c)"
    fn="arm_${base}"
    if ! grep -qE "^static void ${fn}\(void\) \{" "$f"; then
      echo "kernels-gen.sh: $f does not define 'static void ${fn}(void) {' matching its filename" >&2
      exit 1
    fi
    echo "#include \"$f\""
    names+=("$fn")
  done
  echo "static void (*const OMXDSP_ARMS[])(void) = {"
  for n in "${names[@]}"; do echo "  $n,"; done
  echo "};"
  echo "#define OMXDSP_ARM_COUNT ((int)(sizeof(OMXDSP_ARMS) / sizeof(OMXDSP_ARMS[0])))"
} > "$dest_suite"
echo "kernels-gen.sh: wrote $dest_suite (${#suite_files[@]} arms)"

# ---- the perturb cases: test/kernels/<name>.perturb.c --------------------------------------------
mapfile -t perturb_files < <(sorted_glob '*.perturb.c')
if [ "${#perturb_files[@]}" -eq 0 ]; then
  echo "kernels-gen.sh: no perturb case files found under test/kernels/" >&2
  exit 1
fi
dest_perturb="$OUT/kernels-perturb.inc.c"
{
  echo "/* GENERATED by tools/kernels-gen.sh from test/kernels/ (sorted by filename) — do not edit, not committed. */"
  names=()
  for f in "${perturb_files[@]}"; do
    base="$(basename "$f" .perturb.c)"
    fn="perturb_${base}"
    if ! grep -qE "^static int ${fn}\(int failed\) \{" "$f"; then
      echo "kernels-gen.sh: $f does not define 'static int ${fn}(int failed) {' matching its filename" >&2
      exit 1
    fi
    echo "#include \"$f\""
    names+=("$fn")
  done
  echo "static int (*const OMXDSP_PERTURBS[])(int) = {"
  for n in "${names[@]}"; do echo "  $n,"; done
  echo "};"
  echo "#define OMXDSP_PERTURB_COUNT ((int)(sizeof(OMXDSP_PERTURBS) / sizeof(OMXDSP_PERTURBS[0])))"
} > "$dest_perturb"
echo "kernels-gen.sh: wrote $dest_perturb (${#perturb_files[@]} cases)"
